-- ============================================================
-- NexusPlay 社群討論區：forum_posts / forum_comments
-- 若你已手動建表，可略過；欄位名稱需與此一致
-- ============================================================

create table if not exists public.forum_posts (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text not null,
  category text not null check (category in (
    'general', 'bug', 'feedback', 'guide',
    'question', 'showcase', 'review', 'multiplayer',
    'meme', 'lore', 'speedrun', 'update'
  )),
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.forum_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.forum_posts (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists forum_posts_game_id_idx on public.forum_posts (game_id, created_at desc);
create index if not exists forum_comments_post_id_idx on public.forum_comments (post_id, created_at asc);

alter table public.forum_posts enable row level security;
alter table public.forum_comments enable row level security;

drop policy if exists "Public read forum posts" on public.forum_posts;
create policy "Public read forum posts"
  on public.forum_posts for select using (true);

drop policy if exists "Authenticated insert forum posts" on public.forum_posts;
create policy "Authenticated insert forum posts"
  on public.forum_posts for insert
  with check (auth.uid() = user_id);

drop policy if exists "Public read forum comments" on public.forum_comments;
create policy "Public read forum comments"
  on public.forum_comments for select using (true);

drop policy if exists "Authenticated insert forum comments" on public.forum_comments;
create policy "Authenticated insert forum comments"
  on public.forum_comments for insert
  with check (auth.uid() = user_id);
