-- ============================================================
-- 平台統一身份：玩家雲端存檔（game_saves）
-- 請在 Supabase Dashboard → SQL Editor 中執行，或 npm run db:game-saves
-- ============================================================

create table if not exists public.game_saves (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  save_data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  constraint game_saves_game_user_unique unique (game_id, user_id)
);

create index if not exists game_saves_game_id_idx on public.game_saves (game_id);
create index if not exists game_saves_user_id_idx on public.game_saves (user_id);

comment on table public.game_saves is
  '玩家在各遊戲的雲端存檔；由平台統一身份 API 讀寫';

-- ----------------------------------------------------------------
-- Row Level Security：玩家僅能讀寫自己的存檔
-- ----------------------------------------------------------------
alter table public.game_saves enable row level security;

drop policy if exists "Players read own game saves" on public.game_saves;
drop policy if exists "Players insert own game saves" on public.game_saves;
drop policy if exists "Players update own game saves" on public.game_saves;

create policy "Players read own game saves"
  on public.game_saves
  for select
  to authenticated
  using (auth.uid() = user_id);

create policy "Players insert own game saves"
  on public.game_saves
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Players update own game saves"
  on public.game_saves
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
