-- ============================================================
-- 舊平台進度遷移：一次性遷移碼（game_legacy_imports）
-- 請在 Supabase Dashboard → SQL Editor 中執行，或 npm run db:legacy-imports
-- ============================================================

create table if not exists public.game_legacy_imports (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games (id) on delete cascade,
  code_hash text not null,
  label text,
  save_data jsonb not null,
  created_by uuid not null references auth.users (id) on delete cascade,
  used_by uuid references auth.users (id) on delete set null,
  used_at timestamptz,
  created_at timestamptz not null default now(),
  constraint game_legacy_imports_game_code_unique unique (game_id, code_hash)
);

create index if not exists game_legacy_imports_game_id_idx
  on public.game_legacy_imports (game_id);

create index if not exists game_legacy_imports_used_by_idx
  on public.game_legacy_imports (used_by)
  where used_by is not null;

comment on table public.game_legacy_imports is
  '創作者為舊平台玩家建立的一次性遷移碼；玩家登入 NexusPlay 後兌換';

alter table public.game_legacy_imports enable row level security;

-- 讀寫經平台 API（service role）處理；不開放 client 直接存取
drop policy if exists "No direct client access on legacy imports" on public.game_legacy_imports;
create policy "No direct client access on legacy imports"
  on public.game_legacy_imports
  for all
  to authenticated
  using (false)
  with check (false);
