-- 遊戲頁面內容：截圖畫廊、開發日誌、玩家評論
-- 請在 Supabase Dashboard → SQL Editor 中執行，或 npm run db:game-page

alter table public.games
  add column if not exists gallery_urls jsonb not null default '[]'::jsonb,
  add column if not exists devlog_entries jsonb not null default '[]'::jsonb;

create table if not exists public.game_comments (
  id bigint generated by default as identity primary key,
  game_id bigint not null references public.games (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists game_comments_game_id_idx
  on public.game_comments (game_id, created_at desc);

alter table public.game_comments enable row level security;

drop policy if exists "Public read game comments" on public.game_comments;
create policy "Public read game comments"
  on public.game_comments for select using (true);

drop policy if exists "Authenticated insert game comments" on public.game_comments;
create policy "Authenticated insert game comments"
  on public.game_comments for insert
  with check (auth.uid() = user_id);
