-- ============================================================
-- NexusPlay Supabase 初始化腳本
-- 請在 Supabase Dashboard → SQL Editor 中執行
-- ============================================================

-- 1. 建立 games 資料表
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null,
  cover_url text not null,
  game_url text not null,
  created_at timestamptz not null default now()
);

-- 2. 啟用 Row Level Security
alter table public.games enable row level security;

-- 3. games 資料表政策（公開讀取、允許匿名上傳 — 正式環境建議改為需登入）
drop policy if exists "Public read games" on public.games;
create policy "Public read games"
  on public.games
  for select
  using (true);

drop policy if exists "Allow anon insert games" on public.games;
create policy "Allow anon insert games"
  on public.games
  for insert
  with check (true);

-- 4. 建立 Storage Buckets
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'game-covers',
    'game-covers',
    true,
    5242880,
    array['image/png', 'image/jpeg', 'image/jpg']
  ),
  (
    'game-files',
    'game-files',
    true,
    52428800,
    null
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- 5. Storage 政策 — game-covers（公開讀取 + 匿名上傳）
drop policy if exists "Public read game covers" on storage.objects;
create policy "Public read game covers"
  on storage.objects
  for select
  using (bucket_id = 'game-covers');

drop policy if exists "Allow anon upload game covers" on storage.objects;
create policy "Allow anon upload game covers"
  on storage.objects
  for insert
  with check (bucket_id = 'game-covers');

-- 6. Storage 政策 — game-files（公開讀取 + 匿名上傳）
drop policy if exists "Public read game files" on storage.objects;
create policy "Public read game files"
  on storage.objects
  for select
  using (bucket_id = 'game-files');

drop policy if exists "Allow anon upload game files" on storage.objects;
create policy "Allow anon upload game files"
  on storage.objects
  for insert
  with check (bucket_id = 'game-files');
