-- ============================================================
-- RainyNightFrog Supabase 初始化腳本
-- 請在 Supabase Dashboard → SQL Editor 中執行
-- ============================================================

-- 1. 建立 games 資料表
create table if not exists public.games (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  category text not null,
  cover_url text not null,
  game_url text not null,
  creator_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  plays_count bigint not null default 0,
  rating_avg numeric(3, 2) not null default 0,
  publish_status text not null default 'public',
  tips_enabled boolean not null default false,
  suggested_tip_amount numeric(10, 2),
  status text not null default 'pending',
  constraint games_publish_status_check check (publish_status in ('draft', 'public')),
  constraint games_status_check check (status in ('pending', 'approved', 'rejected'))
);

-- 2. 啟用 Row Level Security
alter table public.games enable row level security;

-- 3. games 資料表政策（詳見 supabase/rls-policies.sql 取得完整安全版）
-- 以下為最小公開讀取；正式環境請執行 rls-policies.sql
drop policy if exists "Public read games" on public.games;
create policy "Public read games"
  on public.games
  for select
  to anon, authenticated
  using (
    publish_status = 'public'
    or (auth.uid() is not null and auth.uid() = creator_id)
  );

-- 4. 建立 Storage Buckets
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'game-covers',
    'game-covers',
    true,
    5242880,
    array['image/png', 'image/jpeg', 'image/jpg']
  ),
  (
    'game-files',
    'game-files',
    true,
    52428800,
    null
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- 5. Storage 政策 — game-covers（公開讀取；上傳政策見 rls-policies.sql）
drop policy if exists "Public read game covers" on storage.objects;
create policy "Public read game covers"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'game-covers');

-- 6. Storage 政策 — game-files（公開讀取；上傳政策見 rls-policies.sql）
drop policy if exists "Public read game files" on storage.objects;
create policy "Public read game files"
  on storage.objects
  for select
  to anon, authenticated
  using (bucket_id = 'game-files');
