/** Maps legacy Chinese API error strings to errors.api translation keys */
export const API_ERROR_KEY_BY_MESSAGE: Record<string, string> = {
  "請先登入": "loginRequired",
  "需要創作者身分才能上傳遊戲": "creatorRequiredUpload",
  "需要創作者身分才能更新遊戲": "creatorRequiredUpdate",
  "需要創作者身分才能刪除遊戲": "creatorRequiredDelete",
  "需要創作者身分才能管理遊戲": "creatorRequiredManage",
  "需要創作者身分才能編輯遊戲": "creatorRequiredEdit",
  "無效的遊戲 ID": "invalidGameId",
  "無效的 ID": "invalidId",
  "找不到此遊戲": "gameNotFound",
  "找不到此貼文": "postNotFound",
  "你沒有權限編輯此遊戲": "noEditPermission",
  "請輸入建議打賞金額": "suggestedTipRequired",
  "請輸入遊戲簡介": "descriptionRequired",
  "請選擇遊戲分類": "categoryRequired",
  "無效的遊戲分類": "invalidCategory",
  "請上傳遊戲封面圖": "coverRequired",
  "請上傳遊戲壓縮檔": "zipRequired",
  "封面圖僅支援 .png、.jpg 格式": "coverFormat",
  "遊戲檔案僅支援 .zip 壓縮檔": "zipFormat",
  "zip 根目錄需包含 index.html": "zipMissingIndex",
  "zip 內需包含 index.html": "zipMissingIndex",
  "頭像僅支援 .png、.jpg、.webp 格式": "avatarFormat",
  "頭像不可超過 2 MB": "avatarTooLarge",
  "請選擇頭像圖片": "avatarRequired",
  "請輸入顯示名稱": "displayNameRequired",
  "個人網站網址格式不正確": "websiteInvalid",
  "請先登入才能參與討論": "loginRequiredForum",
  "請輸入貼文標題": "postTitleRequired",
  "請輸入貼文內容": "postContentRequired",
  "請選擇有效的貼文分類": "postCategoryInvalid",
  "請輸入回覆內容": "replyRequired",
  "發布新版本需上傳新的 .zip 遊戲包": "newVersionZipRequired",
  "讀取遊戲失敗": "loadGameFailed",
  "讀取遊戲列表失敗": "loadGamesFailed",
  "讀取討論區失敗": "loadForumFailed",
  "讀取回覆失敗": "loadRepliesFailed",
  "讀取貼文失敗": "loadPostFailed",
  "發布討論失敗": "postFailed",
  "發表回覆失敗": "replyFailed",
  "讀取個人資料失敗": "loadProfileFailed",
  "更新個人資料失敗": "updateProfileFailed",
  "頭像上傳失敗": "avatarUploadFailed",
  "更新遊玩次數失敗": "updatePlayCountFailed",
  "上傳失敗，請稍後再試": "uploadFailed",
  "更新失敗，請稍後再試": "updateFailed",
  "讀取遊戲資料失敗": "loadGameDataFailed",
  "更新過程發生未知錯誤": "updateUnknown",
  "上傳過程發生未知錯誤": "uploadUnknown",
  "讀取創作者遊戲失敗": "loadCreatorGamesFailed",
  "刪除遊戲失敗": "deleteGameFailed",
  "讀取分析資料失敗": "analyticsLoadFailed",
  "讀取收益資料失敗": "revenueLoadFailed",
  "需要創作者身分": "creatorRequiredManage",
  "Failed to load analytics": "analyticsLoadFailed",
  "Failed to load revenue data": "revenueLoadFailed",
  "Failed to load revenue": "revenueLoadFailed",
  "Failed to fetch": "networkError",
  "fetch failed": "networkError",
  "NetworkError": "networkError",
  "Load failed": "analyticsLoadFailed",
  "讀取未綁定遊戲失敗": "loadCreatorGamesFailed",
  "LEGACY_IMPORTS_TABLE_MISSING": "legacyImportsTableMissing",
  "讀取遷移碼失敗": "legacyImportLoadFailed",
  "建立遷移碼失敗": "legacyImportCreateFailed",
};
