import type { VirtualPlayerLocale } from "@/lib/virtual-players";

export type AmbientChatSingle = {
  locale: VirtualPlayerLocale;
  content: string;
};

export type AmbientChatDialogue = {
  locale: VirtualPlayerLocale;
  lines: [string, string];
};

/** 單句：口語、短、像真人在世界頻道隨口說的 */
export const AMBIENT_CHAT_SINGLES: AmbientChatSingle[] = [
  // ── zh-HK ──
  { locale: "zh-HK", content: "有人玩緊 void gacha 嗎" },
  { locale: "zh-HK", content: "剛剛抽咗十連 得一件藍 心態崩" },
  { locale: "zh-HK", content: "個塔防第八波點先升級好啲" },
  { locale: "zh-HK", content: "今晚邊個開黑" },
  { locale: "zh-HK", content: "neon 個 boss 雷射好難躲" },
  { locale: "zh-HK", content: "登入咗先可以上傳分數架" },
  { locale: "zh-HK", content: "cyber fortune 配對有時要等幾分鐘" },
  { locale: "zh-HK", content: "個站載入幾快 唔錯" },
  { locale: "zh-HK", content: "打賞點開架" },
  { locale: "zh-HK", content: "signal breach 第六關開始好燒腦" },
  { locale: "zh-HK", content: "剛註冊 介面幾順" },
  { locale: "zh-HK", content: "節奏遊戲 fever 好爽" },
  { locale: "zh-HK", content: "卡牌 roguelike 打咗成晚" },
  { locale: "zh-HK", content: "邊度改頭像" },
  { locale: "zh-HK", content: "論壇個 bug 回報有人理嗎" },
  { locale: "zh-HK", content: "core defense 輸送帶搞到頭都大" },
  { locale: "zh-HK", content: "void relay 第五層 boss 打唔過" },
  { locale: "zh-HK", content: "軌道塔防第五波開始好癲" },
  { locale: "zh-HK", content: "唔係 點解我 guest 上唔到榜" },
  { locale: "zh-HK", content: "剛剛斷線 分數冇咗 😭" },
  { locale: "zh-HK", content: "有冇人知 pulse protocol 點解 perfect 好難" },
  { locale: "zh-HK", content: "凌晨三點仲有人 真係唔使瞓" },
  { locale: "zh-HK", content: "收藏遊戲喺邊 搵唔到" },
  { locale: "zh-HK", content: "個 gacha 出金率好似好慘" },
  { locale: "zh-HK", content: "跑酷衝刺冷卻好難抓" },
  { locale: "zh-HK", content: "ice protocol 倒數好緊張" },
  { locale: "zh-HK", content: "今日手氣差到爆" },
  { locale: "zh-HK", content: "邊個玩緊 cyber 012" },
  { locale: "zh-HK", content: "論壇個帖回得好慢" },
  { locale: "zh-HK", content: "頭像點upload" },
  { locale: "zh-HK", content: "剛剛一發入魂 爽" },
  { locale: "zh-HK", content: "塔防自動下一波好方便" },
  { locale: "zh-HK", content: "有人試過軌道回收未" },
  { locale: "zh-HK", content: "節奏遊戲 hard 模式手殘" },
  { locale: "zh-HK", content: "卡牌遊戲第三層開始好難" },
  { locale: "zh-HK", content: "呢個站幾新 人唔多" },
  { locale: "zh-HK", content: "剛剛打賞咗個作者 幾毫鬆" },
  { locale: "zh-HK", content: "void gacha 深淵 floor 7 卡我兩日" },
  { locale: "zh-HK", content: "邊個有 core defense 攻略" },
  { locale: "zh-HK", content: "剛剛連輸五把 唔玩了" },
  { locale: "zh-HK", content: "手機玩節奏遊戲好難按" },
  { locale: "zh-HK", content: "喂 邊個幫我睇下點解載入卡住" },
  { locale: "zh-HK", content: "剛剛差一點就破紀錄 氣死" },
  { locale: "zh-HK", content: "開住直播打 手震咗" },
  { locale: "zh-HK", content: "有冇人知成就點解鎖" },
  { locale: "zh-HK", content: "follow 咗個創作者 佢作品幾正" },
  { locale: "zh-HK", content: "邊個要一齊衝榜" },
  { locale: "zh-HK", content: "飲緊珍珠奶茶打遊戲 好頹" },
  { locale: "zh-HK", content: "個音效太大聲 點調細" },
  { locale: "zh-HK", content: "第一次玩塔防 完全唔識起塔" },
  { locale: "zh-HK", content: "剛剛被隊友坑 其實係單機" },
  { locale: "zh-HK", content: "呢個時間仲有人 香港夜貓？" },
  { locale: "zh-HK", content: "卡關卡到想摔機" },
  { locale: "zh-HK", content: "有冇人試過用平板玩" },
  { locale: "zh-HK", content: "剛剛隨機玩到個好好笑嘅 bug" },
  { locale: "zh-HK", content: "邊個遊戲最消磨時間 推介下" },
  { locale: "zh-HK", content: "打完一局先發現冇登入 白打" },
  { locale: "zh-HK", content: "個排行榜頭三名好離譜" },
  { locale: "zh-HK", content: "今晚運氣好似好啲" },
  { locale: "zh-HK", content: "邊度睇返自己打賞記錄" },
  { locale: "zh-HK", content: "剛剛教個朋友註冊 佢話幾易" },
  { locale: "zh-HK", content: "有冇人鍾意節奏多過塔防" },
  { locale: "zh-HK", content: "打咗三個鐘 眼都花" },
  { locale: "zh-HK", content: "試玩版載入完先至知幾好玩" },
  { locale: "zh-HK", content: "唔該講聲邊個遊戲最適合新手" },
  { locale: "zh-HK", content: "食咗飯未 我仲未食" },
  { locale: "zh-HK", content: "返工返到傻 返嚟打兩把先" },
  { locale: "zh-HK", content: "落雨唔想出街 留喺屋企打机" },
  { locale: "zh-HK", content: "今日好熱 冷氣開到最大打遊戲" },
  { locale: "zh-HK", content: "放工喇 終於可以打机" },
  { locale: "zh-HK", content: "考試完 報復性打遊戲" },
  { locale: "zh-HK", content: "屋企人話我成日打机 佢哋唔明" },
  { locale: "zh-HK", content: "邊個仲喺度 唔使瞓架" },
  { locale: "zh-HK", content: "剛沖完涼 手仲濕就開打" },
  { locale: "zh-HK", content: "邊度有冷氣 手汗打唔到節奏" },
  { locale: "zh-HK", content: "今日 mood 差 打遊戲發洩下" },
  { locale: "zh-HK", content: "等外賣等到手痕 先打一局" },
  { locale: "zh-HK", content: "周末計劃：打遊戲 冇第二樣" },
  { locale: "zh-HK", content: "阿媽叫食飯 等陣先" },
  { locale: "zh-HK", content: "又係你 成日喺度" },
  { locale: "zh-HK", content: "有冇人聽緊歌打遊戲" },
  { locale: "zh-HK", content: "靜音打 唔想嘈住屋企人" },
  { locale: "zh-HK", content: "wifi 又 lag 救命" },
  { locale: "zh-HK", content: "用流量打 心痛但想玩" },
  { locale: "zh-HK", content: "啊啊啊 差一啲就過關" },
  { locale: "zh-HK", content: "又死 呢個 boss 有冇搞錯" },
  { locale: "zh-HK", content: "救命 被圍住咗" },
  { locale: "zh-HK", content: "頂 啱啱明明閃到" },
  { locale: "zh-HK", content: "痴線 一 hit 就冇" },
  { locale: "zh-HK", content: "笑死 個怪自己撞牆" },
  { locale: "zh-HK", content: "gg 又輸" },
  { locale: "zh-HK", content: "終於過咗 手都震" },
  { locale: "zh-HK", content: "無血了 點打" },
  { locale: "zh-HK", content: "呢波怪太多 頂唔順" },
  { locale: "zh-HK", content: "雷射嚟喇 唔好企中間" },
  { locale: "zh-HK", content: "衝刺 cd 未好 又中" },
  { locale: "zh-HK", content: "塔放錯位 重嚟" },
  { locale: "zh-HK", content: "第八波嚟喇 準備" },
  { locale: "zh-HK", content: "升級升錯 慘" },
  { locale: "zh-HK", content: "combo 斷咗 心態崩" },
  { locale: "zh-HK", content: "perfect 連續十個 爽" },
  { locale: "zh-HK", content: "fever 入咗 衝" },
  { locale: "zh-HK", content: "倒數三秒 好緊張" },
  { locale: "zh-HK", content: "hack 成功 鬆一啖氣" },
  { locale: "zh-HK", content: "被發現 重嚟" },
  { locale: "zh-HK", content: "抽卡 唔好係藍" },
  { locale: "zh-HK", content: "出金喇！！！" },
  { locale: "zh-HK", content: "又係藍 習慣咗" },
  { locale: "zh-HK", content: "保底仲差幾多抽" },
  { locale: "zh-HK", content: "深淵 floor 8 啲怪好硬" },
  { locale: "zh-HK", content: "卡牌手牌爛到笑" },
  { locale: "zh-HK", content: "roguelike 第三層 又係死局" },
  { locale: "zh-HK", content: "賽博撲克 對面牌好靚" },
  { locale: "zh-HK", content: "all in 輸晒 唔玩" },
  { locale: "zh-HK", content: "軌道回收 第五波 頂" },
  { locale: "zh-HK", content: "新星炮升咗先 唔係過唔到" },
  { locale: "zh-HK", content: "core defense 輸送帶塞車" },
  { locale: "zh-HK", content: "neon 第三關 雷射密到離譜" },
  { locale: "zh-HK", content: "void relay 第六層 迷路" },
  { locale: "zh-HK", content: "ice protocol 倒數 手震" },
  { locale: "zh-HK", content: "signal breach 第七關 燒腦" },
  { locale: "zh-HK", content: "pulse 狂熱 手指唔跟" },
  { locale: "zh-HK", content: "塔防自動下一波 唔使按 正" },
  { locale: "zh-HK", content: "跑酷 差一啲就破紀錄 嬲" },
  { locale: "zh-HK", content: "榜一 幾多分先上得" },
  { locale: "zh-HK", content: "我排第幾 搵唔到" },
  { locale: "zh-HK", content: "有人衝榜 跟唔跟" },
  { locale: "zh-HK", content: "guest 打嘅分唔計 白打" },
  { locale: "zh-HK", content: "登入先 upload 分 記住" },
  { locale: "zh-HK", content: "論壇有人貼攻略 有用" },
  { locale: "zh-HK", content: "bug 回報有人理 幾快" },
  { locale: "zh-HK", content: "收藏咗 遲啲再玩" },
  { locale: "zh-HK", content: "邊個遊戲 bgm 最好聽" },
  { locale: "zh-HK", content: "靜音玩 唔知歌幾好聽" },
  { locale: "zh-HK", content: "試玩版 玩完想買完整版" },
  { locale: "zh-HK", content: "打賞咗五蚊 支持作者" },
  { locale: "zh-HK", content: "follow 咗 等更新" },
  { locale: "zh-HK", content: "作者幾日冇更新 等緊" },
  { locale: "zh-HK", content: "新版本 有咩改" },
  { locale: "zh-HK", content: "難度降咗 終於過到" },
  { locale: "zh-HK", content: "改完更難 作者搞咩" },
  { locale: "zh-HK", content: "手機玩 畫面細 但都 ok" },
  { locale: "zh-HK", content: "平板 節奏好啲" },
  { locale: "zh-HK", content: "電腦全屏 爽" },
  { locale: "zh-HK", content: "載入中... 等咗一分鐘" },
  { locale: "zh-HK", content: "刷新咗 分數冇咗 慘" },
  { locale: "zh-HK", content: "斷線重連 分數保留 正" },
  { locale: "zh-HK", content: "邊個要一齊吐槽" },
  { locale: "zh-HK", content: "今日手气 ok 多打幾把" },
  { locale: "zh-HK", content: "連贏三把 收手" },
  { locale: "zh-HK", content: "再輸就瞓 講咗三次" },
  { locale: "zh-HK", content: "最後一把 真係最後" },
  { locale: "zh-HK", content: "贏咗 可以瞓" },

  // ── zh-CN ──
  { locale: "zh-CN", content: "有人在吗" },
  { locale: "zh-CN", content: "刚打完一把塔防 手都酸了" },
  { locale: "zh-CN", content: "void gacha 这关打了半小时" },
  { locale: "zh-CN", content: "十连全是白的 服了" },
  { locale: "zh-CN", content: "这网站加载还挺快" },
  { locale: "zh-CN", content: "跑酷那个冲刺冷却好难抓" },
  { locale: "zh-CN", content: "有没有人玩赛博扑克" },
  { locale: "zh-CN", content: "打赏开了没" },
  { locale: "zh-CN", content: "排行榜要登录才上传吧" },
  { locale: "zh-CN", content: "刚发现可以收藏游戏" },
  { locale: "zh-CN", content: "卡牌第三层boss好难" },
  { locale: "zh-CN", content: "论坛怎么发帖啊" },
  { locale: "zh-CN", content: "夜里人好像多一点" },
  { locale: "zh-CN", content: "黑客那个倒数好紧张" },
  { locale: "zh-CN", content: "有人一起刷分吗" },
  { locale: "zh-CN", content: "core defense 传送带搞不明白" },
  { locale: "zh-CN", content: "轨道塔防第五波开始变态" },
  { locale: "zh-CN", content: "刚断线 分数没了" },
  { locale: "zh-CN", content: "为啥我游客上不了榜" },
  { locale: "zh-CN", content: "节奏游戏 fever 模式上头" },
  { locale: "zh-CN", content: "void relay 第五层打不过" },
  { locale: "zh-CN", content: "今天手气烂完了" },
  { locale: "zh-CN", content: "头像在哪改" },
  { locale: "zh-CN", content: "凌晨三点还有人 都不睡的吗" },
  { locale: "zh-CN", content: "gacha 出金率感觉好低" },
  { locale: "zh-CN", content: "刚一发入魂 舒服了" },
  { locale: "zh-CN", content: "塔防第八波怎么过啊" },
  { locale: "zh-CN", content: "cyber fortune 匹配要等好久" },
  { locale: "zh-CN", content: "论坛回复好慢" },
  { locale: "zh-CN", content: "连输五把 不玩了" },
  { locale: "zh-CN", content: "手机玩节奏好难按" },
  { locale: "zh-CN", content: "signal breach 第六关开始烧脑" },
  { locale: "zh-CN", content: "这站挺新的 人不多" },
  { locale: "zh-CN", content: "打赏走 Stripe 会真扣款的" },
  { locale: "zh-CN", content: "neon boss 激光躲不过" },
  { locale: "zh-CN", content: "有人试过轨道回收没" },
  { locale: "zh-CN", content: "卡牌 roguelike 打了一晚上" },
  { locale: "zh-CN", content: "刚注册 界面挺顺" },
  { locale: "zh-CN", content: "谁有 core defense 攻略" },
  { locale: "zh-CN", content: "pulse perfect 好难打" },
  { locale: "zh-CN", content: "边玩边听歌还行" },
  { locale: "zh-CN", content: "有人帮看下为啥一直加载中吗" },
  { locale: "zh-CN", content: "差一点破纪录 气死我了" },
  { locale: "zh-CN", content: "边打边喝奶茶 太堕落了" },
  { locale: "zh-CN", content: "成就怎么解锁啊 找不到说明" },
  { locale: "zh-CN", content: "关注了那个作者 作品挺有意思" },
  { locale: "zh-CN", content: "谁要一起冲榜" },
  { locale: "zh-CN", content: "音效太大声了 怎么调小" },
  { locale: "zh-CN", content: "第一次玩塔防 完全不会摆塔" },
  { locale: "zh-CN", content: "卡关卡到想砸键盘" },
  { locale: "zh-CN", content: "有人用平板玩过吗 手感咋样" },
  { locale: "zh-CN", content: "刚碰到个巨好笑的 bug" },
  { locale: "zh-CN", content: "哪个游戏最杀时间 推荐下" },
  { locale: "zh-CN", content: "打完才发现没登录 白打了" },
  { locale: "zh-CN", content: "榜前三分数也太离谱了" },
  { locale: "zh-CN", content: "今晚运气好像好点了" },
  { locale: "zh-CN", content: "打赏记录在哪看" },
  { locale: "zh-CN", content: "刚教朋友注册 他说挺简单" },
  { locale: "zh-CN", content: "有人更喜欢节奏还是塔防" },
  { locale: "zh-CN", content: "打了三个小时 眼睛都花了" },
  { locale: "zh-CN", content: "试玩版加载完才知道多好玩" },
  { locale: "zh-CN", content: "哪个最适合新手 求推荐" },
  { locale: "zh-CN", content: "这个点还有人 都不上班吗" },
  { locale: "zh-CN", content: "开黑吗 虽然好像都是单机" },
  { locale: "zh-CN", content: "吃饭没 我还没吃" },
  { locale: "zh-CN", content: "上班上傻了 回来打两把" },
  { locale: "zh-CN", content: "下雨不想出门 宅家打游戏" },
  { locale: "zh-CN", content: "今天好热 空调开最大打游戏" },
  { locale: "zh-CN", content: "下班了 终于可以打了" },
  { locale: "zh-CN", content: "考完试 报复性打游戏" },
  { locale: "zh-CN", content: "家里说我老打游戏 他们不懂" },
  { locale: "zh-CN", content: "谁还在 都不用睡吗" },
  { locale: "zh-CN", content: "刚洗完澡 手还湿就开打" },
  { locale: "zh-CN", content: "手汗打不了节奏 烦" },
  { locale: "zh-CN", content: "今天心情差 打两把发泄" },
  { locale: "zh-CN", content: "等外卖等到手痒 先打一局" },
  { locale: "zh-CN", content: "周末计划：打游戏 没别的" },
  { locale: "zh-CN", content: "妈叫吃饭 等会" },
  { locale: "zh-CN", content: "又是你 老在这" },
  { locale: "zh-CN", content: "有人边听歌边打吗" },
  { locale: "zh-CN", content: "静音打 不想吵家人" },
  { locale: "zh-CN", content: "wifi又卡 救命" },
  { locale: "zh-CN", content: "用流量打 心疼但想玩" },
  { locale: "zh-CN", content: "啊啊啊 差一点就过了" },
  { locale: "zh-CN", content: "又死了 这boss有病吧" },
  { locale: "zh-CN", content: "救命 被围了" },
  { locale: "zh-CN", content: "靠 明明闪了还中" },
  { locale: "zh-CN", content: "离谱 一碰就死" },
  { locale: "zh-CN", content: "笑死 怪自己撞墙了" },
  { locale: "zh-CN", content: "gg 又输" },
  { locale: "zh-CN", content: "终于过了 手都在抖" },
  { locale: "zh-CN", content: "没血了 怎么打" },
  { locale: "zh-CN", content: "这波怪太多 顶不住" },
  { locale: "zh-CN", content: "激光来了 别站中间" },
  { locale: "zh-CN", content: "冲刺cd没好 又中" },
  { locale: "zh-CN", content: "塔放错了 重来" },
  { locale: "zh-CN", content: "第八波来了 准备" },
  { locale: "zh-CN", content: "升级升错了 惨" },
  { locale: "zh-CN", content: "combo断了 心态崩" },
  { locale: "zh-CN", content: "perfect连十个 爽" },
  { locale: "zh-CN", content: "fever进了 冲" },
  { locale: "zh-CN", content: "倒数三秒 好紧张" },
  { locale: "zh-CN", content: "hack成功 松口气" },
  { locale: "zh-CN", content: "被发现了 重来" },
  { locale: "zh-CN", content: "抽卡 别是蓝的" },
  { locale: "zh-CN", content: "出金了！！！" },
  { locale: "zh-CN", content: "又是蓝 习惯了" },
  { locale: "zh-CN", content: "保底还差几抽" },
  { locale: "zh-CN", content: "深渊8层怪好硬" },
  { locale: "zh-CN", content: "卡牌手牌烂到笑" },
  { locale: "zh-CN", content: "roguelike第三层又是死局" },
  { locale: "zh-CN", content: "赛博扑克对面牌好" },
  { locale: "zh-CN", content: "all in输光 不玩了" },
  { locale: "zh-CN", content: "轨道回收第五波 顶" },
  { locale: "zh-CN", content: "新星炮升了才过得了" },
  { locale: "zh-CN", content: "core defense传送带塞车" },
  { locale: "zh-CN", content: "neon第三关激光密到离谱" },
  { locale: "zh-CN", content: "void relay第六层迷路" },
  { locale: "zh-CN", content: "ice protocol倒数手抖" },
  { locale: "zh-CN", content: "signal breach第七关烧脑" },
  { locale: "zh-CN", content: "pulse狂热手指跟不上" },
  { locale: "zh-CN", content: "塔防自动下一波不用按 舒服" },
  { locale: "zh-CN", content: "跑酷差一点破纪录 气" },
  { locale: "zh-CN", content: "榜一多少分才能上" },
  { locale: "zh-CN", content: "我排第几 找不到" },
  { locale: "zh-CN", content: "有人冲榜 跟不跟" },
  { locale: "zh-CN", content: "游客分不算 白打" },
  { locale: "zh-CN", content: "登录才upload分 记住" },
  { locale: "zh-CN", content: "论坛有人贴攻略 有用" },
  { locale: "zh-CN", content: "bug反馈有人理 挺快" },
  { locale: "zh-CN", content: "收藏了 晚点再玩" },
  { locale: "zh-CN", content: "哪个游戏bgm最好听" },
  { locale: "zh-CN", content: "静音玩 不知道歌多好听" },
  { locale: "zh-CN", content: "试玩版玩完想买完整版" },
  { locale: "zh-CN", content: "打赏了五块 支持作者" },
  { locale: "zh-CN", content: "关注了 等更新" },
  { locale: "zh-CN", content: "作者几天没更新 等着" },
  { locale: "zh-CN", content: "新版本改了啥" },
  { locale: "zh-CN", content: "难度降了 终于过了" },
  { locale: "zh-CN", content: "改完更难 作者搞啥" },
  { locale: "zh-CN", content: "手机玩画面小但还行" },
  { locale: "zh-CN", content: "平板节奏好点" },
  { locale: "zh-CN", content: "电脑全屏 爽" },
  { locale: "zh-CN", content: "加载中...等了一分钟" },
  { locale: "zh-CN", content: "刷新了分数没了 惨" },
  { locale: "zh-CN", content: "断线重连分数保留 好" },
  { locale: "zh-CN", content: "谁要一起吐槽" },
  { locale: "zh-CN", content: "今天手气ok多打几把" },
  { locale: "zh-CN", content: "连赢三把收手" },
  { locale: "zh-CN", content: "再输就睡 说了三次" },
  { locale: "zh-CN", content: "最后一把 真是最后" },
  { locale: "zh-CN", content: "赢了可以睡了" },

  // ── en ──
  { locale: "en", content: "anyone playing void gacha rn" },
  { locale: "en", content: "just got wrecked on wave 12 lol" },
  { locale: "en", content: "tower defense wave 8 is no joke" },
  { locale: "en", content: "how do tips work on this site" },
  { locale: "en", content: "site loads pretty fast ngl" },
  { locale: "en", content: "how do you upload to leaderboard" },
  { locale: "en", content: "cyber fortune matchmaking slow tonight" },
  { locale: "en", content: "card roguelike is addictive" },
  { locale: "en", content: "need login for scores right" },
  { locale: "en", content: "rhythm fever mode goes hard" },
  { locale: "en", content: "anyone beat ice protocol lvl 9" },
  { locale: "en", content: "just signed up ui looks clean" },
  { locale: "en", content: "void gacha rates feel rough" },
  { locale: "en", content: "who else cant sleep and gaming" },
  { locale: "en", content: "forum post button where lol" },
  { locale: "en", content: "conveyor belts in core defense broke my brain" },
  { locale: "en", content: "lost 5 runs in a row im done" },
  { locale: "en", content: "guest scores dont count right" },
  { locale: "en", content: "neon boss triple laser is unfair" },
  { locale: "en", content: "just hit a lucky pull lets go" },
  { locale: "en", content: "orbital salvage wave 5 spikes hard" },
  { locale: "en", content: "void relay floor 5 boss stuck me" },
  { locale: "en", content: "3am gang still here" },
  { locale: "en", content: "mobile rhythm is brutal" },
  { locale: "en", content: "where do u change avatar" },
  { locale: "en", content: "disconnected and lost my run rip" },
  { locale: "en", content: "tipped a creator earlier pretty smooth" },
  { locale: "en", content: "signal breach timer gives me anxiety" },
  { locale: "en", content: "anyone got core defense strats" },
  { locale: "en", content: "pulse perfect windows feel tiny" },
  { locale: "en", content: "site feels pretty new low traffic" },
  { locale: "en", content: "favorites button took me a minute to find" },
  { locale: "en", content: "ten pull all blues pain" },
  { locale: "en", content: "auto next wave in td is nice" },
  { locale: "en", content: "card game layer 3 suddenly spikes" },
  { locale: "en", content: "cyber 012 hard mode is sweaty" },
  { locale: "en", content: "forum replies kinda slow" },
  { locale: "en", content: "listening to music while grinding" },
  { locale: "en", content: "dash cooldown on runner feels awkward" },
  { locale: "en", content: "anyone else bad at rhythm games" },
  { locale: "en", content: "stuck on loading anyone else" },
  { locale: "en", content: "missed high score by like 200 pts pain" },
  { locale: "en", content: "boba tea and gaming peak lifestyle" },
  { locale: "en", content: "how do achievements unlock btw" },
  { locale: "en", content: "followed a creator their game slaps" },
  { locale: "en", content: "who tryna grind leaderboard tonight" },
  { locale: "en", content: "sfx way too loud where settings" },
  { locale: "en", content: "first td run no idea what to build" },
  { locale: "en", content: "stuck on this level bout to rage quit" },
  { locale: "en", content: "tablet play ok or nah" },
  { locale: "en", content: "just hit the funniest bug ever" },
  { locale: "en", content: "best time killer game here?" },
  { locale: "en", content: "finished run then realized not logged in bruh" },
  { locale: "en", content: "top 3 scores are insane how" },
  { locale: "en", content: "luck turning around tonight maybe" },
  { locale: "en", content: "where tip history at" },
  { locale: "en", content: "got my friend to sign up they liked it" },
  { locale: "en", content: "rhythm or td which u prefer" },
  { locale: "en", content: "3hr session eyes dying" },
  { locale: "en", content: "browser build loaded and im hooked ngl" },
  { locale: "en", content: "best beginner friendly game?" },
  { locale: "en", content: "why r ppl awake at this hour lol" },
  { locale: "en", content: "one more run then sleep (lying)" },
  { locale: "en", content: "anyone eat yet im starving" },
  { locale: "en", content: "work was brutal need a game break" },
  { locale: "en", content: "raining outside perfect gaming weather" },
  { locale: "en", content: "ac on max its too hot to think" },
  { locale: "en", content: "finally off work lets goooo" },
  { locale: "en", content: "post exam gaming binge incoming" },
  { locale: "en", content: "parents dont get why i game lol" },
  { locale: "en", content: "who else still up no sleep gang" },
  { locale: "en", content: "just showered hands still wet starting anyway" },
  { locale: "en", content: "sweaty hands rhythm game is pain" },
  { locale: "en", content: "bad mood day gaming therapy" },
  { locale: "en", content: "waiting on food delivery one run first" },
  { locale: "en", content: "weekend plans: games nothing else" },
  { locale: "en", content: "mom called dinner brb" },
  { locale: "en", content: "u again always here huh" },
  { locale: "en", content: "music on while grinding anyone" },
  { locale: "en", content: "muted so i dont wake ppl" },
  { locale: "en", content: "wifi lagging help" },
  { locale: "en", content: "on mobile data rip my bill" },
  { locale: "en", content: "NOOO one hp away from clearing" },
  { locale: "en", content: "died again this boss is bs" },
  { locale: "en", content: "surrounded send help" },
  { locale: "en", content: "i dodged that how did i get hit" },
  { locale: "en", content: "one shot kill are u kidding" },
  { locale: "en", content: "lmao enemy walked into a wall" },
  { locale: "en", content: "gg another L" },
  { locale: "en", content: "finally cleared hands shaking" },
  { locale: "en", content: "no hp left how am i supposed to win" },
  { locale: "en", content: "too many mobs this wave insane" },
  { locale: "en", content: "laser incoming dont stand middle" },
  { locale: "en", content: "dash on cd got clipped rip" },
  { locale: "en", content: "placed tower wrong restart time" },
  { locale: "en", content: "wave 8 here we go" },
  { locale: "en", content: "upgraded wrong thing pain" },
  { locale: "en", content: "combo broke mental collapse" },
  { locale: "en", content: "ten perfects in a row lets go" },
  { locale: "en", content: "fever mode activated send it" },
  { locale: "en", content: "3 sec countdown im sweating" },
  { locale: "en", content: "hack succeeded exhale" },
  { locale: "en", content: "got spotted run it back" },
  { locale: "en", content: "gacha pull pls not blue" },
  { locale: "en", content: "GOLD PULL LETS GOOO" },
  { locale: "en", content: "all blues again whatever" },
  { locale: "en", content: "how many til pity again" },
  { locale: "en", content: "abyss floor 8 mobs tanky af" },
  { locale: "en", content: "card hand so bad its funny" },
  { locale: "en", content: "roguelike layer 3 dead run again" },
  { locale: "en", content: "cyber poker opponent had nuts" },
  { locale: "en", content: "all in and lost im out" },
  { locale: "en", content: "orbital salvage wave 5 hurts" },
  { locale: "en", content: "nova turret upgrade or u die wave 5" },
  { locale: "en", content: "core defense conveyor jammed lol" },
  { locale: "en", content: "neon stage 3 lasers everywhere" },
  { locale: "en", content: "void relay floor 6 got lost" },
  { locale: "en", content: "ice protocol timer hands shaking" },
  { locale: "en", content: "signal breach lvl 7 brain melt" },
  { locale: "en", content: "pulse fever fingers not keeping up" },
  { locale: "en", content: "td auto next wave is clutch" },
  { locale: "en", content: "runner missed record by a hair mad" },
  { locale: "en", content: "what score even is rank 1" },
  { locale: "en", content: "where am i on leaderboard cant find" },
  { locale: "en", content: "anyone grinding lb tonight" },
  { locale: "en", content: "guest run doesnt count wasted" },
  { locale: "en", content: "login before score upload remember" },
  { locale: "en", content: "forum guide actually helped" },
  { locale: "en", content: "bug report got answered fast nice" },
  { locale: "en", content: "favorited for later" },
  { locale: "en", content: "best bgm on this site go" },
  { locale: "en", content: "played muted missed the banger soundtrack" },
  { locale: "en", content: "demo hooked me ngl" },
  { locale: "en", content: "tipped creator five bucks support" },
  { locale: "en", content: "followed waiting on update" },
  { locale: "en", content: "dev quiet few days waiting" },
  { locale: "en", content: "new patch what changed" },
  { locale: "en", content: "difficulty nerfed finally beat it" },
  { locale: "en", content: "patch made it harder dev why" },
  { locale: "en", content: "mobile screen small but playable" },
  { locale: "en", content: "tablet rhythm feels better" },
  { locale: "en", content: "fullscreen on pc hits different" },
  { locale: "en", content: "loading forever one min in" },
  { locale: "en", content: "refreshed lost score tragic" },
  { locale: "en", content: "reconnected score saved W" },
  { locale: "en", content: "anyone wanna vent about this level" },
  { locale: "en", content: "luck decent today few more runs" },
  { locale: "en", content: "three wins in a row quitting while ahead" },
  { locale: "en", content: "one more loss and im sleeping (3rd time)" },
  { locale: "en", content: "last run for real this time" },
  { locale: "en", content: "won ok sleep time" },
];

/** 對答：兩句能接上，像真人在頻道裡聊 */
export const AMBIENT_CHAT_DIALOGUES: AmbientChatDialogue[] = [
  // ── zh-HK ──
  { locale: "zh-HK", lines: ["有人玩 core defense 嗎", "有啊 第十二關卡我三日"] },
  { locale: "zh-HK", lines: ["打賞掣喺邊", "創作者後台有得設定 我試過"] },
  { locale: "zh-HK", lines: ["個 gacha 要課先", "唔使吧 慢慢打都得"] },
  { locale: "zh-HK", lines: ["neon 個衝刺幾時用", "雷射預警出現就先切線再衝"] },
  { locale: "zh-HK", lines: ["點解我上唔到榜", "要登入先計分架"] },
  { locale: "zh-HK", lines: ["邊個玩緊節奏", "我 狂熱難度手殘中"] },
  { locale: "zh-HK", lines: ["論壇點發帖", "入遊戲頁面下面有討論區"] },
  { locale: "zh-HK", lines: ["卡牌遊戲有掛嗎", "唔知喎 自己打啦"] },
  { locale: "zh-HK", lines: ["void relay 難唔難", "第五層開始先難 前面還好"] },
  { locale: "zh-HK", lines: ["軌道塔防有人玩嗎", "有 第五波開始要升新星炮"] },
  { locale: "zh-HK", lines: ["十連全藍正常嗎", "太正常了 我習慣了"] },
  { locale: "zh-HK", lines: ["ice protocol 點過關", "先清巡邏路線 唔好硬闖"] },
  { locale: "zh-HK", lines: ["呢個站幾時開嘅", "好似都幾新 人唔多"] },
  { locale: "zh-HK", lines: ["手機玩得順嗎", "節奏有啲難按 其他 ok"] },
  { locale: "zh-HK", lines: ["邊個有攻略", "論壇有人貼 你搜下"] },
  { locale: "zh-HK", lines: ["剛剛斷線", "重新整理再登入試下"] },
  { locale: "zh-HK", lines: ["cyber 012 難嗎", "普通 ok hard 好虐"] },
  { locale: "zh-HK", lines: ["收藏喺邊", "遊戲頁面右上角心形"] },
  { locale: "zh-HK", lines: ["凌晨仲有人？", "有啊 瞓唔着"] },
  { locale: "zh-HK", lines: ["塔防第八波點過", "先升核心 炮塔唔好亂起"] },
  { locale: "zh-HK", lines: ["剛剛一發入魂", "恭喜 我羨慕"] },
  { locale: "zh-HK", lines: ["打賞會真扣錢？", "會㗎 Stripe 處理"] },
  { locale: "zh-HK", lines: ["pulse fever 點觸發", "連擊夠就會入"] },
  { locale: "zh-HK", lines: ["邊個玩 void gacha", "我 深淵7卡緊"] },
  { locale: "zh-HK", lines: ["成就點睇", "個人頁面有得睇 你入去搵下"] },
  { locale: "zh-HK", lines: ["邊個遊戲最難", "睇人啦 我節奏最慘"] },
  { locale: "zh-HK", lines: ["剛剛破咗自己紀錄", "勁啊 幾多分"] },
  { locale: "zh-HK", lines: ["有冇人知點 follow 創作者", "創作者頁面有個掣"] },
  { locale: "zh-HK", lines: ["載入好慢", "清 cache 或者換 browser 試"] },
  { locale: "zh-HK", lines: ["今晚有人開黑嗎", "呢度好似冇真正聯機"] },
  { locale: "zh-HK", lines: ["邊個遊戲音效最好", "neon 個 bgm 幾正"] },
  { locale: "zh-HK", lines: ["剛剛被嚇親", "咩事 關卡 jump scare？"] },
  { locale: "zh-HK", lines: ["平板玩得順嗎", "節奏一般 塔防 ok"] },
  { locale: "zh-HK", lines: ["邊個要交換心得", "我可以講塔防"] },
  { locale: "zh-HK", lines: ["打咗成晚值唔值", "開心就值啦"] },
  { locale: "zh-HK", lines: ["個站有冇手機 app", "好似淨係 web"] },
  { locale: "zh-HK", lines: ["邊個遊戲最適合打發時間", "gacha 同 roguelike 都好殺"] },
  { locale: "zh-HK", lines: ["剛剛隨機玩到個 bug", "截圖去論壇啦"] },
  { locale: "zh-HK", lines: ["食咗飯未", "未 打緊第八波"] },
  { locale: "zh-HK", lines: ["又死咗", "咩關 我幫你睇"] },
  { locale: "zh-HK", lines: ["差一啲就過", "唔好放 再嚟"] },
  { locale: "zh-HK", lines: ["救命 被雷射夾住", "衝刺切線 唔好硬食"] },
  { locale: "zh-HK", lines: ["十連又係藍", "正常 我上星期都係"] },
  { locale: "zh-HK", lines: ["出金喇", "哇 幾多抽"] },
  { locale: "zh-HK", lines: ["combo 斷咗", "節奏遊戲常事 唔使嬲"] },
  { locale: "zh-HK", lines: ["fever 入咗", "跟住打 唔好停"] },
  { locale: "zh-HK", lines: ["塔防第八波點過", "升核心 炮塔唔好亂起"] },
  { locale: "zh-HK", lines: ["輸送帶塞車", "先清前面 唔好堆"] },
  { locale: "zh-HK", lines: ["neon 第三關好難", "雷射預警出現就切"] },
  { locale: "zh-HK", lines: ["void relay 迷路", "跟地圖標記 唔好亂行"] },
  { locale: "zh-HK", lines: ["ice 倒數好緊張", "先清巡邏 唔好急"] },
  { locale: "zh-HK", lines: ["signal breach 卡關", "第六關開始要計好步數"] },
  { locale: "zh-HK", lines: ["賽博撲克輸晒", "唔 all in 就唔會"] },
  { locale: "zh-HK", lines: ["卡牌手牌爛", "roguelike 咁 下把"] },
  { locale: "zh-HK", lines: ["榜一幾多分", "我睇咗 離譜到"] },
  { locale: "zh-HK", lines: ["guest 上唔到榜", "登入先計分架"] },
  { locale: "zh-HK", lines: ["斷線分數冇咗", "試下重新整理 有時保留"] },
  { locale: "zh-HK", lines: ["wifi lag", "換 4g 或者等陣"] },
  { locale: "zh-HK", lines: ["手機玩得順嗎", "節奏難按 塔防 ok"] },
  { locale: "zh-HK", lines: ["邊個遊戲最殺時間", "gacha 同 roguelike"] },
  { locale: "zh-HK", lines: ["打賞咗作者", "幾蚊 支持吓"] },
  { locale: "zh-HK", lines: ["作者幾日冇更新", "可能忙 等吓"] },
  { locale: "zh-HK", lines: ["難度降咗", "終於過到 多謝 patch"] },
  { locale: "zh-HK", lines: ["改完更難", "去論壇講 作者會睇"] },
  { locale: "zh-HK", lines: ["最後一把", "我聽咗十次"] },
  { locale: "zh-HK", lines: ["贏咗可以瞓", "我仲未 再一把"] },
  { locale: "zh-HK", lines: ["返工累", "打兩把先 唔使理"] },
  { locale: "zh-HK", lines: ["落雨留喺屋企", "正 打足成日"] },
  { locale: "zh-HK", lines: ["邊度改頭像", "個人頁面右上角"] },
  { locale: "zh-HK", lines: ["成就點解鎖", "打遊戲自然會出 你睇個人頁"] },
  { locale: "zh-HK", lines: ["論壇點發帖", "遊戲頁下面 討論區"] },
  { locale: "zh-HK", lines: ["有冇攻略", "論壇有人貼 搜下"] },
  { locale: "zh-HK", lines: ["深淵7卡兩日", "升裝備先 唔好硬打"] },
  { locale: "zh-HK", lines: ["軌道第五波", "新星炮升咗未"] },
  { locale: "zh-HK", lines: ["pulse perfect 好難", "練普通先 唔使急"] },
  { locale: "zh-HK", lines: ["跑酷差一點破紀", "記低路線 聽日再衝"] },
  { locale: "zh-HK", lines: ["靜音玩", "開聲先至知 bgm 幾正"] },

  // ── zh-CN ──
  { locale: "zh-CN", lines: ["这游戏要氪吗", "不用吧 慢慢玩就行"] },
  { locale: "zh-CN", lines: ["在吗在吗", "在 刚打完一把"] },
  { locale: "zh-CN", lines: ["排行榜怎么上传", "登录后打游戏会自动传"] },
  { locale: "zh-CN", lines: ["塔防第八波怎么过", "先升核心再铺炮塔"] },
  { locale: "zh-CN", lines: ["跑酷boss怎么躲", "看预警先换道再冲刺"] },
  { locale: "zh-CN", lines: ["打赏开了吗", "游戏页有打赏按钮 走 Stripe"] },
  { locale: "zh-CN", lines: ["论坛在哪", "游戏页面往下翻就有"] },
  { locale: "zh-CN", lines: ["有人联机吗", "这好像都是单机游戏"] },
  { locale: "zh-CN", lines: ["void relay 难不难", "第五层开始难 前面还行"] },
  { locale: "zh-CN", lines: ["十连全蓝正常吗", "太正常了 我都习惯了"] },
  { locale: "zh-CN", lines: ["轨道塔防有人玩吗", "有 第五波要升新星炮"] },
  { locale: "zh-CN", lines: ["ice protocol 怎么过", "先清巡逻路线 别硬闯"] },
  { locale: "zh-CN", lines: ["这站什么时候开的", "感觉挺新 人不多"] },
  { locale: "zh-CN", lines: ["手机玩得顺吗", "节奏有点难按 其他还行"] },
  { locale: "zh-CN", lines: ["刚断线了", "刷新重新登录试试"] },
  { locale: "zh-CN", lines: ["cyber 012 难吗", "普通还行 hard 很虐"] },
  { locale: "zh-CN", lines: ["收藏在哪", "游戏页面右上角爱心"] },
  { locale: "zh-CN", lines: ["凌晨还有人？", "有啊 睡不着"] },
  { locale: "zh-CN", lines: ["刚一发入魂", "恭喜 我酸了"] },
  { locale: "zh-CN", lines: ["pulse fever 怎么触发", "连击够了就会进"] },
  { locale: "zh-CN", lines: ["谁玩 void gacha", "我 深渊7卡着"] },
  { locale: "zh-CN", lines: ["卡牌游戏有挂吗", "不知道 自己打吧"] },
  { locale: "zh-CN", lines: ["攻略在哪", "论坛有人发 你搜下"] },
  { locale: "zh-CN", lines: ["游客能上榜吗", "不能 要登录"] },
  { locale: "zh-CN", lines: ["成就在哪看", "个人页面有 你进去找找"] },
  { locale: "zh-CN", lines: ["哪个游戏最难", "看人啊 我节奏最惨"] },
  { locale: "zh-CN", lines: ["刚破了自己纪录", "牛啊 多少分"] },
  { locale: "zh-CN", lines: ["怎么关注创作者", "创作者页面有个按钮"] },
  { locale: "zh-CN", lines: ["加载好慢", "清缓存或者换浏览器试试"] },
  { locale: "zh-CN", lines: ["今晚有人开黑吗", "这好像没有真联机"] },
  { locale: "zh-CN", lines: ["哪个游戏音效最好", "neon 的 bgm 不错"] },
  { locale: "zh-CN", lines: ["刚被吓了一跳", "咋了 关卡 jump scare？"] },
  { locale: "zh-CN", lines: ["平板玩得顺吗", "节奏一般 塔防还行"] },
  { locale: "zh-CN", lines: ["谁要交流心得", "我可以讲塔防"] },
  { locale: "zh-CN", lines: ["打了一晚上值不值", "开心就值"] },
  { locale: "zh-CN", lines: ["这站有手机 app 吗", "好像就 web"] },
  { locale: "zh-CN", lines: ["哪个最适合打发时间", "gacha 和 roguelike 都挺杀时间"] },
  { locale: "zh-CN", lines: ["刚碰到个 bug", "截图发论坛吧"] },
  { locale: "zh-CN", lines: ["吃饭没", "没 打着第八波呢"] },
  { locale: "zh-CN", lines: ["又死了", "哪关 我帮你看"] },
  { locale: "zh-CN", lines: ["差一点就过", "别放 再来"] },
  { locale: "zh-CN", lines: ["救命 被激光夹了", "冲刺换道 别硬吃"] },
  { locale: "zh-CN", lines: ["十连又是蓝", "正常 我上周也是"] },
  { locale: "zh-CN", lines: ["出金了", "哇 几抽出的"] },
  { locale: "zh-CN", lines: ["combo断了", "节奏游戏常事 别气"] },
  { locale: "zh-CN", lines: ["fever进了", "跟着打 别停"] },
  { locale: "zh-CN", lines: ["塔防第八波怎么过", "升核心 炮塔别乱起"] },
  { locale: "zh-CN", lines: ["传送带塞车", "先清前面 别堆"] },
  { locale: "zh-CN", lines: ["neon第三关好难", "激光预警出现就切"] },
  { locale: "zh-CN", lines: ["void relay迷路", "跟地图标记 别乱走"] },
  { locale: "zh-CN", lines: ["ice倒数好紧张", "先清巡逻 别急"] },
  { locale: "zh-CN", lines: ["signal breach卡关", "第六关开始要算步数"] },
  { locale: "zh-CN", lines: ["赛博扑克输光", "不all in就不会"] },
  { locale: "zh-CN", lines: ["卡牌手牌烂", "roguelike这样 下把"] },
  { locale: "zh-CN", lines: ["榜一多少分", "我看了 离谱"] },
  { locale: "zh-CN", lines: ["游客上不了榜", "登录才计分"] },
  { locale: "zh-CN", lines: ["断线分数没了", "试试刷新 有时保留"] },
  { locale: "zh-CN", lines: ["wifi卡", "换4g或者等会"] },
  { locale: "zh-CN", lines: ["手机玩得顺吗", "节奏难按 塔防还行"] },
  { locale: "zh-CN", lines: ["哪个最杀时间", "gacha和roguelike"] },
  { locale: "zh-CN", lines: ["打赏了作者", "几块 支持下"] },
  { locale: "zh-CN", lines: ["作者几天没更新", "可能忙 等等"] },
  { locale: "zh-CN", lines: ["难度降了", "终于过了 谢谢patch"] },
  { locale: "zh-CN", lines: ["改完更难", "去论坛说 作者会看"] },
  { locale: "zh-CN", lines: ["最后一把", "我听过十次了"] },
  { locale: "zh-CN", lines: ["赢了可以睡了", "我还没 再来一把"] },
  { locale: "zh-CN", lines: ["上班累", "打两把 不用理"] },
  { locale: "zh-CN", lines: ["下雨宅家", "正好 打一整天"] },
  { locale: "zh-CN", lines: ["头像在哪改", "个人页右上角"] },
  { locale: "zh-CN", lines: ["成就怎么解锁", "打游戏自然会出 看个人页"] },
  { locale: "zh-CN", lines: ["论坛怎么发帖", "游戏页下面 讨论区"] },
  { locale: "zh-CN", lines: ["有攻略吗", "论坛有人发 搜下"] },
  { locale: "zh-CN", lines: ["深渊7卡两天", "升装备先 别硬打"] },
  { locale: "zh-CN", lines: ["轨道第五波", "新星炮升了没"] },
  { locale: "zh-CN", lines: ["pulse perfect好难", "练普通先 别急"] },
  { locale: "zh-CN", lines: ["跑酷差一点破纪录", "记下路线 明天再冲"] },
  { locale: "zh-CN", lines: ["静音玩", "开声才知道bgm多好听"] },

  // ── en ──
  { locale: "en", lines: ["anyone on cyber fortune", "yeah stuck on hard mode"] },
  { locale: "en", lines: ["how to tip creators", "game page has a tip button i think"] },
  { locale: "en", lines: ["is this site new", "feels like early access yeah"] },
  { locale: "en", lines: ["void gacha worth it", "free to try just dont expect much"] },
  { locale: "en", lines: ["leaderboard not updating", "u logged in? guest scores dont count"] },
  { locale: "en", lines: ["wave 15 boss tips", "dodge middle lane on triple laser"] },
  { locale: "en", lines: ["anyone beat rhythm fever", "not yet 94% accuracy max"] },
  { locale: "en", lines: ["where forum", "scroll down on the game page"] },
  { locale: "en", lines: ["void relay hard?", "floor 5+ is where it hurts"] },
  { locale: "en", lines: ["ten pull all blues", "welcome to the club"] },
  { locale: "en", lines: ["orbital salvage tips", "upgrade nova turret before wave 5"] },
  { locale: "en", lines: ["ice protocol stuck", "clear patrol routes first"] },
  { locale: "en", lines: ["mobile playable?", "rhythm is rough rest is ok"] },
  { locale: "en", lines: ["just disconnected", "refresh and log back in"] },
  { locale: "en", lines: ["anyone awake", "yeah 3am grind"] },
  { locale: "en", lines: ["got a lucky pull", "nice im jealous"] },
  { locale: "en", lines: ["tips real money?", "yeah stripe handles it"] },
  { locale: "en", lines: ["favorites where", "heart icon on game page"] },
  { locale: "en", lines: ["core defense help", "upgrade core before spamming turrets"] },
  { locale: "en", lines: ["card game cheats?", "idk just play it"] },
  { locale: "en", lines: ["guide anywhere", "forum has threads search it"] },
  { locale: "en", lines: ["pulse fever how", "stack combo til it pops"] },
  { locale: "en", lines: ["playing void gacha?", "yeah stuck abyss 7"] },
  { locale: "en", lines: ["coop?", "think its all solo browser games"] },
  { locale: "en", lines: ["where achievements", "profile page should list em"] },
  { locale: "en", lines: ["hardest game here", "depends rhythm wrecks me"] },
  { locale: "en", lines: ["just beat my personal best", "nice what score"] },
  { locale: "en", lines: ["how to follow creators", "button on their page"] },
  { locale: "en", lines: ["loading forever", "clear cache or diff browser"] },
  { locale: "en", lines: ["party up tonight", "pretty sure no real mp here"] },
  { locale: "en", lines: ["best soundtrack", "neon bgm goes hard imo"] },
  { locale: "en", lines: ["got jumpscared lol", "what happened which game"] },
  { locale: "en", lines: ["tablet ok?", "rhythm meh td fine"] },
  { locale: "en", lines: ["wanna trade tips", "i can yap about td"] },
  { locale: "en", lines: ["all nighter worth it", "if ur having fun yeah"] },
  { locale: "en", lines: ["mobile app?", "think its web only"] },
  { locale: "en", lines: ["best time sink", "gacha and roguelike both"] },
  { locale: "en", lines: ["found a weird bug", "screenshot and post forum"] },
  { locale: "en", lines: ["u eat yet", "nah grinding wave 8"] },
  { locale: "en", lines: ["died again", "which stage i can help"] },
  { locale: "en", lines: ["so close to clearing", "dont quit one more"] },
  { locale: "en", lines: ["lasers got me sandwiched", "dash to side lane dont tank it"] },
  { locale: "en", lines: ["ten pull all blue again", "normal i got that last week"] },
  { locale: "en", lines: ["GOLD PULL", "nice how many pulls in"] },
  { locale: "en", lines: ["combo broke", "rhythm games man happens"] },
  { locale: "en", lines: ["fever mode on", "keep going dont stop"] },
  { locale: "en", lines: ["td wave 8 tips", "upgrade core dont spam turrets"] },
  { locale: "en", lines: ["conveyor jammed", "clear front first dont stack"] },
  { locale: "en", lines: ["neon stage 3 brutal", "switch lanes on laser warning"] },
  { locale: "en", lines: ["void relay lost", "follow map markers"] },
  { locale: "en", lines: ["ice timer stressing me", "clear patrol routes first"] },
  { locale: "en", lines: ["signal breach stuck", "lvl 6+ count your moves"] },
  { locale: "en", lines: ["lost everything in poker", "dont all in lol"] },
  { locale: "en", lines: ["trash card hand", "roguelike rng next run"] },
  { locale: "en", lines: ["rank 1 score what", "checked it insane"] },
  { locale: "en", lines: ["guest cant rank", "login for scores"] },
  { locale: "en", lines: ["dc lost score", "try refresh sometimes saves"] },
  { locale: "en", lines: ["wifi lagging", "mobile data or wait"] },
  { locale: "en", lines: ["mobile ok?", "rhythm rough td fine"] },
  { locale: "en", lines: ["best time sink", "gacha and roguelike"] },
  { locale: "en", lines: ["tipped the dev", "few bucks support"] },
  { locale: "en", lines: ["dev quiet lately", "probably busy wait"] },
  { locale: "en", lines: ["difficulty nerfed", "finally beat it ty patch"] },
  { locale: "en", lines: ["patch made it harder", "forum post dev reads em"] },
  { locale: "en", lines: ["last run then sleep", "heard that ten times"] },
  { locale: "en", lines: ["won ok bedtime", "not me one more"] },
  { locale: "en", lines: ["work killed me", "few runs unwind"] },
  { locale: "en", lines: ["rainy day inside", "perfect gaming day"] },
  { locale: "en", lines: ["change avatar where", "profile top right"] },
  { locale: "en", lines: ["how unlock achievements", "just play check profile"] },
  { locale: "en", lines: ["how post on forum", "game page scroll to discussion"] },
  { locale: "en", lines: ["any guides", "forum threads search it"] },
  { locale: "en", lines: ["stuck abyss 7 two days", "upgrade gear dont brute force"] },
  { locale: "en", lines: ["orbital wave 5", "nova turret upgraded yet"] },
  { locale: "en", lines: ["pulse perfect hard", "practice normal first"] },
  { locale: "en", lines: ["missed record by hair", "memorize route try tmr"] },
  { locale: "en", lines: ["playing muted", "turn sfx on bgm slaps"] },
];

/** 創作者頻道：單句 */
export const AMBIENT_CREATOR_SINGLES: AmbientChatSingle[] = [
  { locale: "zh-HK", content: "剛上傳咗新版本 有空幫手試玩畀意見" },
  { locale: "zh-HK", content: "打賞已經開通 玩家可以直接支持" },
  { locale: "zh-HK", content: "封面圖尺寸有冇人知 上傳頁寫得唔清" },
  { locale: "zh-HK", content: "草稿 save 咗先 聽日先公開" },
  { locale: "zh-HK", content: "論壇有人回報 bug 記得去答" },
  { locale: "zh-HK", content: "平台費而家 0% 早期上傳幾抵" },
  { locale: "zh-HK", content: "devlog 更新咗 順便改咗簡介" },
  { locale: "zh-HK", content: "analytics 瀏覽數好似延遲幾分鐘" },
  { locale: "zh-HK", content: "新版本上咗 歡迎去試" },
  { locale: "zh-HK", content: "個遊戲 iframe 尺寸點調好啲" },
  { locale: "zh-HK", content: "有人用過 api key 未" },
  { locale: "zh-HK", content: "今晚改咗平衡 聽日再推一版" },
  { locale: "zh-HK", content: "玩家留言話太難 我諗緊點改" },
  { locale: "zh-HK", content: "封面換咗張 舊嗰張太暗" },
  { locale: "zh-HK", content: "論壇帖冇人回 有啲尷尬" },
  { locale: "zh-CN", content: "刚传了个新版本 有空帮忙试试给反馈" },
  { locale: "zh-CN", content: "打赏已经开通 玩家可以直接支持" },
  { locale: "zh-CN", content: "封面图尺寸有要求吗 上传页没写太清楚" },
  { locale: "zh-CN", content: "先存草稿了 明天再改公开" },
  { locale: "zh-CN", content: "论坛有人报 bug 记得回复一下" },
  { locale: "zh-CN", content: "早期平台费 0% 现在上传挺划算" },
  { locale: "zh-CN", content: "更新了 devlog 顺便改了简介" },
  { locale: "zh-CN", content: "后台浏览数据好像会延迟几分钟" },
  { locale: "zh-CN", content: "新版本上了 欢迎来试" },
  { locale: "zh-CN", content: "游戏 iframe 尺寸怎么调比较好" },
  { locale: "zh-CN", content: "有人用过 api key 吗" },
  { locale: "zh-CN", content: "今晚改了平衡 明天再推一版" },
  { locale: "zh-CN", content: "玩家留言说太难 我在想要不要改" },
  { locale: "zh-CN", content: "封面换了张 旧那张太暗" },
  { locale: "zh-CN", content: "论坛帖没人回 有点尴尬" },
  { locale: "en", content: "just uploaded a new build — feedback welcome" },
  { locale: "en", content: "tips are live now players can support directly" },
  { locale: "en", content: "what cover size do you guys use for uploads" },
  { locale: "en", content: "saved as draft going public tomorrow" },
  { locale: "en", content: "someone reported a bug on my thread gotta check" },
  { locale: "en", content: "0% platform fee during early access is nice" },
  { locale: "en", content: "posted a devlog update and tweaked the description" },
  { locale: "en", content: "analytics page views seem a few mins behind" },
  { locale: "en", content: "new build is up if anyone wants to try" },
  { locale: "en", content: "how do u guys size the game iframe" },
  { locale: "en", content: "anyone using api keys yet" },
  { locale: "en", content: "nerfed balance tonight pushing again tomorrow" },
  { locale: "en", content: "player said its too hard debating a patch" },
  { locale: "en", content: "swapped cover art old one was too dark" },
  { locale: "en", content: "forum thread got zero replies kinda awkward" },
  { locale: "zh-HK", content: "寫緊更新說明 有冇人幫手睇吓文法" },
  { locale: "zh-HK", content: "個遊戲 tag 揀咩好 選擇困難" },
  { locale: "zh-HK", content: "有人留言話想要難度選項 考慮緊" },
  { locale: "zh-HK", content: "上傳咗新版 舊 bug 應該修咗" },
  { locale: "zh-HK", content: "宣傳帖發咗 冇咩反應 正常" },
  { locale: "zh-HK", content: "想加多語言 但翻譯好貴" },
  { locale: "zh-HK", content: "手機版效能仲要優化" },
  { locale: "zh-HK", content: "有人問幾時出正式版 我都唔知" },
  { locale: "zh-HK", content: "今晚打算改 UI 配色" },
  { locale: "zh-HK", content: "收到第一個打賞 好開心" },
  { locale: "zh-HK", content: "個遊戲載入時間要再壓縮" },
  { locale: "zh-HK", content: "考慮開個 discord 傾計" },
  { locale: "zh-HK", content: "玩家建議加教學關 有道理" },
  { locale: "zh-CN", content: "在写更新说明 有人帮忙看下文案吗" },
  { locale: "zh-CN", content: "游戏 tag 选什么好 选择困难" },
  { locale: "zh-CN", content: "有人留言想要难度选项 在考虑" },
  { locale: "zh-CN", content: "上传了新版本 旧 bug 应该修了" },
  { locale: "zh-CN", content: "宣传帖发了 没啥反应 正常吧" },
  { locale: "zh-CN", content: "想加多语言 翻译好贵" },
  { locale: "zh-CN", content: "手机版性能还要优化" },
  { locale: "zh-CN", content: "有人问啥时候正式版 我也不知道" },
  { locale: "zh-CN", content: "今晚准备改下界面配色" },
  { locale: "zh-CN", content: "收到第一个打赏 挺开心" },
  { locale: "zh-CN", content: "游戏加载时间还得再压缩" },
  { locale: "zh-CN", content: "考虑开个 discord 聊聊" },
  { locale: "zh-CN", content: "玩家建议加教学关 有道理" },
  { locale: "en", content: "writing patch notes anyone wanna proofread" },
  { locale: "en", content: "genre tags are hard to pick ngl" },
  { locale: "en", content: "player asked for difficulty options thinking about it" },
  { locale: "en", content: "pushed new build old bug should be fixed" },
  { locale: "en", content: "promo post got crickets normal i guess" },
  { locale: "en", content: "want localization but translation $$" },
  { locale: "en", content: "mobile perf still needs work" },
  { locale: "en", content: "someone asked release date idk yet" },
  { locale: "en", content: "tweaking ui colors tonight" },
  { locale: "en", content: "got my first tip hype" },
  { locale: "en", content: "load time needs more compression" },
  { locale: "en", content: "thinking about a discord for feedback" },
  { locale: "en", content: "tutorial level suggestion actually makes sense" },
  { locale: "zh-HK", content: "debug 咗成晚 終於搵到個 null reference" },
  { locale: "zh-HK", content: "玩家話太簡單 我唔知點改" },
  { locale: "zh-HK", content: "第一個 five star review 好感動" },
  { locale: "zh-HK", content: "upload 失敗 檔案太大 要再壓" },
  { locale: "zh-HK", content: "試玩版同完整版分開上傳 定一齊" },
  { locale: "zh-HK", content: "有人問可唔可以加手柄支持 考慮緊" },
  { locale: "zh-HK", content: "美術自己畫 好慢但省錢" },
  { locale: "zh-HK", content: "音效用免費素材 要標 credit" },
  { locale: "zh-HK", content: "排行榜有人刷分 點處理好" },
  { locale: "zh-HK", content: "devlog 寫咗半個鐘 冇人睇都寫" },
  { locale: "zh-HK", content: "週末推 bug fix 版 唔加新內容" },
  { locale: "zh-HK", content: "玩家建議加存檔 有道理 排期緊" },
  { locale: "zh-HK", content: "iframe 喺手機會裁切 要改 css" },
  { locale: "zh-HK", content: "收到 bug report 多謝截圖" },
  { locale: "zh-HK", content: "平衡改完自己試 仲係太難" },
  { locale: "zh-HK", content: "想加成就系統 但 sdk 要睇下" },
  { locale: "zh-HK", content: "封面換咗 瀏覽數好似升咗少少" },
  { locale: "zh-HK", content: "論壇回覆慢 因為一個人做" },
  { locale: "zh-HK", content: "有冇人試過 zip 打包 有咩坑" },
  { locale: "zh-HK", content: "早期 0% 費 趁住多上幾個" },
  { locale: "zh-HK", content: "玩家話 bgm 太大 下版調細" },
  { locale: "zh-HK", content: "教學關寫完 自己玩覺得太長" },
  { locale: "zh-HK", content: "考慮加 easy mode 唔想太簡單" },
  { locale: "zh-HK", content: "analytics 顯示第八波流失最高" },
  { locale: "zh-HK", content: "多語言先做英文 其他後補" },
  { locale: "zh-HK", content: "discord 開咗 歡迎入嚟報 bug" },
  { locale: "zh-HK", content: "收到打賞留言 多謝支持" },
  { locale: "zh-HK", content: "更新說明寫太長 冇人睇 下次短啲" },
  { locale: "zh-HK", content: "試玩 convert 率低 封面要改" },
  { locale: "zh-HK", content: "同其他創作者交流 學到幾招" },
  { locale: "zh-CN", content: "debug了一晚上 终于找到null reference" },
  { locale: "zh-CN", content: "玩家说太简单 我不知道怎么改" },
  { locale: "zh-CN", content: "第一个五星评价 挺感动" },
  { locale: "zh-CN", content: "上传失败 文件太大 得再压" },
  { locale: "zh-CN", content: "试玩版和完整版分开上传还是一起" },
  { locale: "zh-CN", content: "有人问能不能加手柄 在考虑" },
  { locale: "zh-CN", content: "美术自己画 慢但省钱" },
  { locale: "zh-CN", content: "音效用免费素材 要标credit" },
  { locale: "zh-CN", content: "排行榜有人刷分 怎么处理" },
  { locale: "zh-CN", content: "devlog写了半小时 没人看也写" },
  { locale: "zh-CN", content: "周末推bug fix版 不加新内容" },
  { locale: "zh-CN", content: "玩家建议加存档 有道理 排期中" },
  { locale: "zh-CN", content: "iframe在手机上会裁切 要改css" },
  { locale: "zh-CN", content: "收到bug report 谢谢截图" },
  { locale: "zh-CN", content: "平衡改完自己试 还是太难" },
  { locale: "zh-CN", content: "想加成就系统 sdk得看看" },
  { locale: "zh-CN", content: "封面换了 浏览数好像涨了点" },
  { locale: "zh-CN", content: "论坛回复慢 因为一个人做" },
  { locale: "zh-CN", content: "有人试过zip打包 有啥坑" },
  { locale: "zh-CN", content: "早期0%费 趁现在多上几个" },
  { locale: "zh-CN", content: "玩家说bgm太大 下版调小" },
  { locale: "zh-CN", content: "教学关写完 自己玩觉得太长" },
  { locale: "zh-CN", content: "考虑加easy mode 不想太简单" },
  { locale: "zh-CN", content: "analytics显示第八波流失最高" },
  { locale: "zh-CN", content: "多语言先做英文 其他后补" },
  { locale: "zh-CN", content: "discord开了 欢迎来报bug" },
  { locale: "zh-CN", content: "收到打赏留言 谢谢支持" },
  { locale: "zh-CN", content: "更新说明写太长 没人看 下次短点" },
  { locale: "zh-CN", content: "试玩convert率低 封面要改" },
  { locale: "zh-CN", content: "跟其他创作者交流 学到几招" },
  { locale: "en", content: "debugged all night found the null ref finally" },
  { locale: "en", content: "player said too easy idk how to tune" },
  { locale: "en", content: "first five star review im emotional ngl" },
  { locale: "en", content: "upload failed file too big compress again" },
  { locale: "en", content: "demo vs full build separate uploads?" },
  { locale: "en", content: "controller support request considering it" },
  { locale: "en", content: "doing art myself slow but saves $$" },
  { locale: "en", content: "free sfx pack gotta credit properly" },
  { locale: "en", content: "someone score cheating on lb how handle" },
  { locale: "en", content: "devlog took 30 min nobody reads still worth it" },
  { locale: "en", content: "weekend hotfix no new content" },
  { locale: "en", content: "save system request fair scheduling it" },
  { locale: "en", content: "iframe crops on mobile css fix needed" },
  { locale: "en", content: "bug report with screenshot ty" },
  { locale: "en", content: "balanced it myself still too hard rip" },
  { locale: "en", content: "want achievements sdk docs time" },
  { locale: "en", content: "new cover views bumped a little maybe" },
  { locale: "en", content: "slow forum replies solo dev life" },
  { locale: "en", content: "zip packaging any gotchas" },
  { locale: "en", content: "0% fee early access uploading more while i can" },
  { locale: "en", content: "bgm too loud feedback lowering next patch" },
  { locale: "en", content: "tutorial feels long even to me" },
  { locale: "en", content: "easy mode idea dont wanna trivialize it" },
  { locale: "en", content: "analytics wave 8 biggest dropoff" },
  { locale: "en", content: "localization english first rest later" },
  { locale: "en", content: "discord open for bug reports" },
  { locale: "en", content: "tip with nice message ty support" },
  { locale: "en", content: "patch notes too long nobody reads shorter next time" },
  { locale: "en", content: "demo conversion low maybe cover art" },
  { locale: "en", content: "chatted other devs learned a few tricks" },
];

/** 創作者頻道：對答 */
export const AMBIENT_CREATOR_DIALOGUES: AmbientChatDialogue[] = [
  { locale: "zh-HK", lines: ["審核一般要幾耐", "我上次一日左右"] },
  { locale: "zh-HK", lines: ["打賞點用", "遊戲頁面有掣 走 Stripe"] },
  { locale: "zh-HK", lines: ["封面用 png 定 jpg", "png 清晰啲 檔案大啲"] },
  { locale: "zh-HK", lines: ["devlog 有人睇咩", "有啊 唔多但有人"] },
  { locale: "zh-HK", lines: ["api key 點申請", "設定頁面有 自己 generate"] },
  { locale: "zh-HK", lines: ["玩家話太難要改嗎", "睇數據 流失高先改"] },
  { locale: "zh-HK", lines: ["草稿會過期嗎", "唔會 一直留到"] },
  { locale: "zh-HK", lines: ["analytics 準唔準", "大概參考 延遲有"] },
  { locale: "zh-CN", lines: ["审核一般要多久", "我上次一天左右"] },
  { locale: "zh-CN", lines: ["打赏怎么用", "游戏页面有按钮 走 Stripe"] },
  { locale: "zh-CN", lines: ["封面用 png 还是 jpg", "png 清晰 文件大点"] },
  { locale: "zh-CN", lines: ["devlog 有人看吗", "有 不多但有人"] },
  { locale: "zh-CN", lines: ["api key 怎么申请", "设置页面有 自己 generate"] },
  { locale: "zh-CN", lines: ["玩家说太难要改吗", "看数据 流失高再改"] },
  { locale: "zh-CN", lines: ["草稿会过期吗", "不会 一直留着"] },
  { locale: "zh-CN", lines: ["analytics 准吗", "大概参考 有延迟"] },
  { locale: "en", lines: ["how long does review take", "like a day for me last time"] },
  { locale: "en", lines: ["when tips go live", "theyre live on game pages now"] },
  { locale: "en", lines: ["png or jpg for cover", "png sharper bigger file"] },
  { locale: "en", lines: ["anyone read devlogs", "some ppl yeah not many"] },
  { locale: "en", lines: ["how to get api key", "settings page generate one"] },
  { locale: "en", lines: ["game too hard change it?", "check dropoff first"] },
  { locale: "en", lines: ["do drafts expire", "nah they stick around"] },
  { locale: "en", lines: ["analytics accurate?", "roughly yeah bit delayed"] },
  { locale: "zh-HK", lines: ["更新說明寫咩好", "玩家想知改咗咩就得"] },
  { locale: "zh-HK", lines: ["冇人玩點算", "慢慢嚟 宣傳要時間"] },
  { locale: "zh-HK", lines: ["tag 揀幾個夠", "三到五個 唔好塞滿"] },
  { locale: "zh-HK", lines: ["手機 lag 點解決", "減粒子同解析度先"] },
  { locale: "zh-HK", lines: ["有人抄我 idea 點算", "做好自己先啦"] },
  { locale: "zh-HK", lines: ["幾時開放打賞", "已經開咗 去遊戲頁試"] },
  { locale: "zh-HK", lines: ["discord 有人入嗎", "開咗再貼 link"] },
  { locale: "zh-HK", lines: ["教學關會唔會太長", "短啲好 三分鐘內"] },
  { locale: "zh-HK", lines: ["封面 AI 生成得唔得", "記得標 disclosure"] },
  { locale: "zh-CN", lines: ["更新说明写啥好", "玩家想知道改了啥就行"] },
  { locale: "zh-CN", lines: ["没人玩咋办", "慢慢来 宣传要时间"] },
  { locale: "zh-CN", lines: ["tag 选几个够", "三到五个 别塞满"] },
  { locale: "zh-CN", lines: ["手机 lag 怎么解", "先减粒子和分辨率"] },
  { locale: "zh-CN", lines: ["有人抄我创意咋办", "先做好自己的"] },
  { locale: "zh-CN", lines: ["啥时候开放打赏", "已经开了 去游戏页试试"] },
  { locale: "zh-CN", lines: ["discord 有人进吗", "开了再贴链接"] },
  { locale: "zh-CN", lines: ["教学关会不会太长", "短点好 三分钟内"] },
  { locale: "zh-CN", lines: ["封面 AI 生成行吗", "记得标 disclosure"] },
  { locale: "en", lines: ["what to put in patch notes", "just what changed players care"] },
  { locale: "en", lines: ["no players yet help", "takes time keep promoting"] },
  { locale: "en", lines: ["how many tags", "like 3-5 dont spam"] },
  { locale: "en", lines: ["mobile lag fixes", "cut particles res first"] },
  { locale: "en", lines: ["someone copied my idea", "focus on ur own thing"] },
  { locale: "en", lines: ["when tips live", "already live check game page"] },
  { locale: "en", lines: ["discord worth it", "post link when u make one"] },
  { locale: "en", lines: ["tutorial too long?", "keep under 3 min imo"] },
  { locale: "en", lines: ["ai cover art ok?", "yeah just disclose it"] },
  { locale: "zh-HK", lines: ["第八波流失好高", "我諗緊降難度或者加提示"] },
  { locale: "zh-HK", lines: ["upload 一直 fail", "check 檔案大小同格式"] },
  { locale: "zh-HK", lines: ["有人話太難有人話太易", "做難度選項啦"] },
  { locale: "zh-HK", lines: ["打賞幾蚊起", "平台最低幾蚊 你睇設定"] },
  { locale: "zh-HK", lines: ["devlog 有人睇咩", "少但係有用 長期"] },
  { locale: "zh-HK", lines: ["bug 修咗未", "下版推 今晚 build"] },
  { locale: "zh-HK", lines: ["封面自己畫定 AI", "自己畫慢啲 但独特"] },
  { locale: "zh-HK", lines: ["手機 lag 點解", "減粒子 降解析度"] },
  { locale: "zh-HK", lines: ["排行榜刷分", "report 去 admin 睇下"] },
  { locale: "zh-HK", lines: ["想加存檔", "sdk 有 api 我研究緊"] },
  { locale: "zh-HK", lines: ["試玩版幾長好", "五分鐘內 hook 到就得"] },
  { locale: "zh-HK", lines: ["tag 揀咩", "tower defense rhythm 睇類型"] },
  { locale: "zh-HK", lines: ["冇人玩 點宣傳", "論壇 devlog 慢慢嚟"] },
  { locale: "zh-HK", lines: ["收到第一個打賞", "恭喜 我仲未"] },
  { locale: "zh-HK", lines: ["更新頻率幾密", "一個月一版 唔好太密"] },
  { locale: "zh-HK", lines: ["玩家話想要聯機", "單機先做好"] },
  { locale: "zh-HK", lines: ["音效太大", "下版加音量 slider"] },
  { locale: "zh-HK", lines: ["教學關太長", "剪到兩分鐘"] },
  { locale: "zh-HK", lines: ["analytics 邊度睇", "dashboard 入面"] },
  { locale: "zh-HK", lines: ["discord  worth it", "小 community 够用"] },
  { locale: "zh-HK", lines: ["多語言先做邊個", "英文 然後簡中"] },
  { locale: "zh-HK", lines: ["zip 打包注意咩", "index.html 要喺 root"] },
  { locale: "zh-HK", lines: ["審核 reject 點算", "改完再 submit"] },
  { locale: "zh-HK", lines: ["平衡點調", "自己打十把 睇數據"] },
  { locale: "zh-HK", lines: ["封面換咗冇用", "A/B 試下 過幾日睇"] },
  { locale: "zh-HK", lines: ["論壇冇人回", "自己 seed 幾個帖"] },
  { locale: "zh-HK", lines: ["api key 做咩用", "leaderboard 同成就"] },
  { locale: "zh-HK", lines: ["solo dev 累", "正常 慢慢嚟"] },
  { locale: "zh-HK", lines: ["玩家建議加 skin", "好 idea 排後面"] },
  { locale: "zh-CN", lines: ["第八波流失好高", "考虑降难度或加提示"] },
  { locale: "zh-CN", lines: ["upload一直fail", "查文件大小和格式"] },
  { locale: "zh-CN", lines: ["有人说太难有人说太易", "做难度选项吧"] },
  { locale: "zh-CN", lines: ["打赏几块起", "平台最低几块 看设置"] },
  { locale: "zh-CN", lines: ["devlog有人看吗", "少但有用 长期"] },
  { locale: "zh-CN", lines: ["bug修了吗", "下版推 今晚build"] },
  { locale: "zh-CN", lines: ["封面自己画还是AI", "自己画慢点但独特"] },
  { locale: "zh-CN", lines: ["手机lag咋办", "减粒子降分辨率"] },
  { locale: "zh-CN", lines: ["排行榜刷分", "report给admin看看"] },
  { locale: "zh-CN", lines: ["想加存档", "sdk有api我研究呢"] },
  { locale: "zh-CN", lines: ["试玩版多长好", "五分钟内hook到就行"] },
  { locale: "zh-CN", lines: ["tag选啥", "tower defense rhythm看类型"] },
  { locale: "zh-CN", lines: ["没人玩咋宣传", "论坛devlog慢慢来"] },
  { locale: "zh-CN", lines: ["收到第一个打赏", "恭喜 我还没有"] },
  { locale: "zh-CN", lines: ["更新频率多密", "一个月一版别太密"] },
  { locale: "zh-CN", lines: ["玩家想要联机", "单机先做好"] },
  { locale: "zh-CN", lines: ["音效太大", "下版加音量slider"] },
  { locale: "zh-CN", lines: ["教学关太长", "剪到两分钟"] },
  { locale: "zh-CN", lines: ["analytics哪看", "dashboard里面"] },
  { locale: "zh-CN", lines: ["discord值得吗", "小community够用"] },
  { locale: "zh-CN", lines: ["多语言先做哪个", "英文然后简中"] },
  { locale: "zh-CN", lines: ["zip打包注意啥", "index.html要在root"] },
  { locale: "zh-CN", lines: ["审核reject咋办", "改完再submit"] },
  { locale: "zh-CN", lines: ["平衡点调", "自己打十把看数据"] },
  { locale: "zh-CN", lines: ["封面换了没用", "A/B试试过几天看"] },
  { locale: "zh-CN", lines: ["论坛没人回", "自己seed几个帖"] },
  { locale: "zh-CN", lines: ["api key干啥用", "leaderboard和成就"] },
  { locale: "zh-CN", lines: ["solo dev累", "正常 慢慢来"] },
  { locale: "zh-CN", lines: ["玩家建议加skin", "好idea排后面"] },
  { locale: "en", lines: ["wave 8 dropoff huge", "thinking nerf or add hints"] },
  { locale: "en", lines: ["upload keeps failing", "check file size and format"] },
  { locale: "en", lines: ["too hard vs too easy feedback", "difficulty options maybe"] },
  { locale: "en", lines: ["minimum tip amount", "check platform settings"] },
  { locale: "en", lines: ["devlogs worth writing", "small audience long term yes"] },
  { locale: "en", lines: ["bug fixed yet", "next build tonight"] },
  { locale: "en", lines: ["hand drawn or ai cover", "hand slower but unique"] },
  { locale: "en", lines: ["mobile lag help", "cut particles lower res"] },
  { locale: "en", lines: ["lb score cheating", "report to admin"] },
  { locale: "en", lines: ["save system when", "sdk api researching"] },
  { locale: "en", lines: ["demo length ideal", "under 5 min hook em"] },
  { locale: "en", lines: ["which tags pick", "match genre td rhythm etc"] },
  { locale: "en", lines: ["no players promo tips", "forum devlog slow grind"] },
  { locale: "en", lines: ["got first tip congrats", "ty im still waiting lol"] },
  { locale: "en", lines: ["update frequency", "monthly patch dont burn out"] },
  { locale: "en", lines: ["multiplayer requests", "solo polish first"] },
  { locale: "en", lines: ["sfx too loud", "volume slider next patch"] },
  { locale: "en", lines: ["tutorial too long", "cut to 2 min"] },
  { locale: "en", lines: ["where analytics", "dashboard section"] },
  { locale: "en", lines: ["discord worth it", "small community enough"] },
  { locale: "en", lines: ["localization priority", "english then zh"] },
  { locale: "en", lines: ["zip packaging tips", "index.html at root"] },
  { locale: "en", lines: ["review rejected now what", "fix and resubmit"] },
  { locale: "en", lines: ["how tune balance", "play ten runs check data"] },
  { locale: "en", lines: ["new cover no bump", "ab test wait few days"] },
  { locale: "en", lines: ["forum dead", "seed a few threads yourself"] },
  { locale: "en", lines: ["api key for what", "leaderboard achievements"] },
  { locale: "en", lines: ["solo dev exhausting", "normal pace yourself"] },
  { locale: "en", lines: ["skin suggestion", "good idea backlog it"] },
];
