import type { VirtualPlayerLocale } from "@/lib/virtual-players";

export type AmbientChatSingle = {
  locale: VirtualPlayerLocale;
  content: string;
};

export type AmbientChatDialogue = {
  locale: VirtualPlayerLocale;
  lines: [string, string];
};

/** 單句：口語、短、像真人在世界頻道隨口說的 */
export const AMBIENT_CHAT_SINGLES: AmbientChatSingle[] = [
  // ── zh-HK ──
  { locale: "zh-HK", content: "有人玩緊 void gacha 嗎" },
  { locale: "zh-HK", content: "剛剛抽咗十連 得一件藍 心態崩" },
  { locale: "zh-HK", content: "個塔防第八波點先升級好啲" },
  { locale: "zh-HK", content: "今晚邊個開黑" },
  { locale: "zh-HK", content: "neon 個 boss 雷射好難躲" },
  { locale: "zh-HK", content: "登入咗先可以上傳分數架" },
  { locale: "zh-HK", content: "cyber fortune 配對有時要等幾分鐘" },
  { locale: "zh-HK", content: "個站載入幾快 唔錯" },
  { locale: "zh-HK", content: "打賞點開架" },
  { locale: "zh-HK", content: "signal breach 第六關開始好燒腦" },
  { locale: "zh-HK", content: "剛註冊 介面幾順" },
  { locale: "zh-HK", content: "節奏遊戲 fever 好爽" },
  { locale: "zh-HK", content: "卡牌 roguelike 打咗成晚" },
  { locale: "zh-HK", content: "邊度改頭像" },
  { locale: "zh-HK", content: "論壇個 bug 回報有人理嗎" },
  { locale: "zh-HK", content: "core defense 輸送帶搞到頭都大" },
  { locale: "zh-HK", content: "void relay 第五層 boss 打唔過" },
  { locale: "zh-HK", content: "軌道塔防第五波開始好癲" },
  { locale: "zh-HK", content: "唔係 點解我 guest 上唔到榜" },
  { locale: "zh-HK", content: "剛剛斷線 分數冇咗 😭" },
  { locale: "zh-HK", content: "有冇人知 pulse protocol 點解 perfect 好難" },
  { locale: "zh-HK", content: "凌晨三點仲有人 真係唔使瞓" },
  { locale: "zh-HK", content: "收藏遊戲喺邊 搵唔到" },
  { locale: "zh-HK", content: "個 gacha 出金率好似好慘" },
  { locale: "zh-HK", content: "跑酷衝刺冷卻好難抓" },
  { locale: "zh-HK", content: "ice protocol 倒數好緊張" },
  { locale: "zh-HK", content: "今日手氣差到爆" },
  { locale: "zh-HK", content: "邊個玩緊 cyber 012" },
  { locale: "zh-HK", content: "論壇個帖回得好慢" },
  { locale: "zh-HK", content: "頭像點upload" },
  { locale: "zh-HK", content: "剛剛一發入魂 爽" },
  { locale: "zh-HK", content: "塔防自動下一波好方便" },
  { locale: "zh-HK", content: "有人試過軌道回收未" },
  { locale: "zh-HK", content: "節奏遊戲 hard 模式手殘" },
  { locale: "zh-HK", content: "卡牌遊戲第三層開始好難" },
  { locale: "zh-HK", content: "呢個站幾新 人唔多" },
  { locale: "zh-HK", content: "打賞係 preview 唔會真扣錢架" },
  { locale: "zh-HK", content: "void gacha 深淵 floor 7 卡我兩日" },
  { locale: "zh-HK", content: "邊個有 core defense 攻略" },
  { locale: "zh-HK", content: "剛剛連輸五把 唔玩了" },
  { locale: "zh-HK", content: "手機玩節奏遊戲好難按" },

  // ── zh-CN ──
  { locale: "zh-CN", content: "有人在吗" },
  { locale: "zh-CN", content: "刚打完一把塔防 手都酸了" },
  { locale: "zh-CN", content: "void gacha 这关打了半小时" },
  { locale: "zh-CN", content: "十连全是白的 服了" },
  { locale: "zh-CN", content: "这网站加载还挺快" },
  { locale: "zh-CN", content: "跑酷那个冲刺冷却好难抓" },
  { locale: "zh-CN", content: "有没有人玩赛博扑克" },
  { locale: "zh-CN", content: "打赏开了没" },
  { locale: "zh-CN", content: "排行榜要登录才上传吧" },
  { locale: "zh-CN", content: "刚发现可以收藏游戏" },
  { locale: "zh-CN", content: "卡牌第三层boss好难" },
  { locale: "zh-CN", content: "论坛怎么发帖啊" },
  { locale: "zh-CN", content: "夜里人好像多一点" },
  { locale: "zh-CN", content: "黑客那个倒数好紧张" },
  { locale: "zh-CN", content: "有人一起刷分吗" },
  { locale: "zh-CN", content: "core defense 传送带搞不明白" },
  { locale: "zh-CN", content: "轨道塔防第五波开始变态" },
  { locale: "zh-CN", content: "刚断线 分数没了" },
  { locale: "zh-CN", content: "为啥我游客上不了榜" },
  { locale: "zh-CN", content: "节奏游戏 fever 模式上头" },
  { locale: "zh-CN", content: "void relay 第五层打不过" },
  { locale: "zh-CN", content: "今天手气烂完了" },
  { locale: "zh-CN", content: "头像在哪改" },
  { locale: "zh-CN", content: "凌晨三点还有人 都不睡的吗" },
  { locale: "zh-CN", content: "gacha 出金率感觉好低" },
  { locale: "zh-CN", content: "刚一发入魂 舒服了" },
  { locale: "zh-CN", content: "塔防第八波怎么过啊" },
  { locale: "zh-CN", content: "cyber fortune 匹配要等好久" },
  { locale: "zh-CN", content: "论坛回复好慢" },
  { locale: "zh-CN", content: "连输五把 不玩了" },
  { locale: "zh-CN", content: "手机玩节奏好难按" },
  { locale: "zh-CN", content: "signal breach 第六关开始烧脑" },
  { locale: "zh-CN", content: "这站挺新的 人不多" },
  { locale: "zh-CN", content: "打赏好像是预览 不会真扣" },
  { locale: "zh-CN", content: "neon boss 激光躲不过" },
  { locale: "zh-CN", content: "有人试过轨道回收没" },
  { locale: "zh-CN", content: "卡牌 roguelike 打了一晚上" },
  { locale: "zh-CN", content: "刚注册 界面挺顺" },
  { locale: "zh-CN", content: "谁有 core defense 攻略" },
  { locale: "zh-CN", content: "pulse perfect 好难打" },
  { locale: "zh-CN", content: "边玩边听歌还行" },

  // ── en ──
  { locale: "en", content: "anyone playing void gacha rn" },
  { locale: "en", content: "just got wrecked on wave 12 lol" },
  { locale: "en", content: "tower defense wave 8 is no joke" },
  { locale: "en", content: "is tipping actually live or preview" },
  { locale: "en", content: "site loads pretty fast ngl" },
  { locale: "en", content: "how do you upload to leaderboard" },
  { locale: "en", content: "cyber fortune matchmaking slow tonight" },
  { locale: "en", content: "card roguelike is addictive" },
  { locale: "en", content: "need login for scores right" },
  { locale: "en", content: "rhythm fever mode goes hard" },
  { locale: "en", content: "anyone beat ice protocol lvl 9" },
  { locale: "en", content: "just signed up ui looks clean" },
  { locale: "en", content: "void gacha rates feel rough" },
  { locale: "en", content: "who else cant sleep and gaming" },
  { locale: "en", content: "forum post button where lol" },
  { locale: "en", content: "conveyor belts in core defense broke my brain" },
  { locale: "en", content: "lost 5 runs in a row im done" },
  { locale: "en", content: "guest scores dont count right" },
  { locale: "en", content: "neon boss triple laser is unfair" },
  { locale: "en", content: "just hit a lucky pull lets go" },
  { locale: "en", content: "orbital salvage wave 5 spikes hard" },
  { locale: "en", content: "void relay floor 5 boss stuck me" },
  { locale: "en", content: "3am gang still here" },
  { locale: "en", content: "mobile rhythm is brutal" },
  { locale: "en", content: "where do u change avatar" },
  { locale: "en", content: "disconnected and lost my run rip" },
  { locale: "en", content: "tips are preview only i think" },
  { locale: "en", content: "signal breach timer gives me anxiety" },
  { locale: "en", content: "anyone got core defense strats" },
  { locale: "en", content: "pulse perfect windows feel tiny" },
  { locale: "en", content: "site feels pretty new low traffic" },
  { locale: "en", content: "favorites button took me a minute to find" },
  { locale: "en", content: "ten pull all blues pain" },
  { locale: "en", content: "auto next wave in td is nice" },
  { locale: "en", content: "card game layer 3 suddenly spikes" },
  { locale: "en", content: "cyber 012 hard mode is sweaty" },
  { locale: "en", content: "forum replies kinda slow" },
  { locale: "en", content: "listening to music while grinding" },
  { locale: "en", content: "dash cooldown on runner feels awkward" },
  { locale: "en", content: "anyone else bad at rhythm games" },
];

/** 對答：兩句能接上，像真人在頻道裡聊 */
export const AMBIENT_CHAT_DIALOGUES: AmbientChatDialogue[] = [
  // ── zh-HK ──
  { locale: "zh-HK", lines: ["有人玩 core defense 嗎", "有啊 第十二關卡我三日"] },
  { locale: "zh-HK", lines: ["打賞點開架", "創作者後台有得設定 我試過"] },
  { locale: "zh-HK", lines: ["個 gacha 要課先", "唔使吧 慢慢打都得"] },
  { locale: "zh-HK", lines: ["neon 個衝刺幾時用", "雷射預警出現就先切線再衝"] },
  { locale: "zh-HK", lines: ["點解我上唔到榜", "要登入先計分架"] },
  { locale: "zh-HK", lines: ["邊個玩緊節奏", "我 狂熱難度手殘中"] },
  { locale: "zh-HK", lines: ["論壇點發帖", "入遊戲頁面下面有討論區"] },
  { locale: "zh-HK", lines: ["卡牌遊戲有掛嗎", "唔知喎 自己打啦"] },
  { locale: "zh-HK", lines: ["void relay 難唔難", "第五層開始先難 前面還好"] },
  { locale: "zh-HK", lines: ["軌道塔防有人玩嗎", "有 第五波開始要升新星炮"] },
  { locale: "zh-HK", lines: ["十連全藍正常嗎", "太正常了 我習慣了"] },
  { locale: "zh-HK", lines: ["ice protocol 點過關", "先清巡邏路線 唔好硬闖"] },
  { locale: "zh-HK", lines: ["呢個站幾時開嘅", "好似都幾新 人唔多"] },
  { locale: "zh-HK", lines: ["手機玩得順嗎", "節奏有啲難按 其他 ok"] },
  { locale: "zh-HK", lines: ["邊個有攻略", "論壇有人貼 你搜下"] },
  { locale: "zh-HK", lines: ["剛剛斷線", "重新整理再登入試下"] },
  { locale: "zh-HK", lines: ["cyber 012 難嗎", "普通 ok hard 好虐"] },
  { locale: "zh-HK", lines: ["收藏喺邊", "遊戲頁面右上角心形"] },
  { locale: "zh-HK", lines: ["凌晨仲有人？", "有啊 瞓唔着"] },
  { locale: "zh-HK", lines: ["塔防第八波點過", "先升核心 炮塔唔好亂起"] },
  { locale: "zh-HK", lines: ["剛剛一發入魂", "恭喜 我羨慕"] },
  { locale: "zh-HK", lines: ["打賞會真扣錢？", "preview 階段唔會"] },
  { locale: "zh-HK", lines: ["pulse fever 點觸發", "連擊夠就會入"] },
  { locale: "zh-HK", lines: ["邊個玩 void gacha", "我 深淵7卡緊"] },

  // ── zh-CN ──
  { locale: "zh-CN", lines: ["这游戏要氪吗", "不用吧 慢慢玩就行"] },
  { locale: "zh-CN", lines: ["有人在吗", "在 刚打完一把"] },
  { locale: "zh-CN", lines: ["排行榜怎么上传", "登录后打游戏会自动传"] },
  { locale: "zh-CN", lines: ["塔防第八波怎么过", "先升核心再铺炮塔"] },
  { locale: "zh-CN", lines: ["跑酷boss怎么躲", "看预警先换道再冲刺"] },
  { locale: "zh-CN", lines: ["打赏开了吗", "好像还是预览 没真扣款"] },
  { locale: "zh-CN", lines: ["论坛在哪", "游戏页面往下翻就有"] },
  { locale: "zh-CN", lines: ["有人联机吗", "这好像都是单机demo"] },
  { locale: "zh-CN", lines: ["void relay 难不难", "第五层开始难 前面还行"] },
  { locale: "zh-CN", lines: ["十连全蓝正常吗", "太正常了 我都习惯了"] },
  { locale: "zh-CN", lines: ["轨道塔防有人玩吗", "有 第五波要升新星炮"] },
  { locale: "zh-CN", lines: ["ice protocol 怎么过", "先清巡逻路线 别硬闯"] },
  { locale: "zh-CN", lines: ["这站什么时候开的", "感觉挺新 人不多"] },
  { locale: "zh-CN", lines: ["手机玩得顺吗", "节奏有点难按 其他还行"] },
  { locale: "zh-CN", lines: ["刚断线了", "刷新重新登录试试"] },
  { locale: "zh-CN", lines: ["cyber 012 难吗", "普通还行 hard 很虐"] },
  { locale: "zh-CN", lines: ["收藏在哪", "游戏页面右上角爱心"] },
  { locale: "zh-CN", lines: ["凌晨还有人？", "有啊 睡不着"] },
  { locale: "zh-CN", lines: ["刚一发入魂", "恭喜 我酸了"] },
  { locale: "zh-CN", lines: ["pulse fever 怎么触发", "连击够了就会进"] },
  { locale: "zh-CN", lines: ["谁玩 void gacha", "我 深渊7卡着"] },
  { locale: "zh-CN", lines: ["卡牌游戏有挂吗", "不知道 自己打吧"] },
  { locale: "zh-CN", lines: ["攻略在哪", "论坛有人发 你搜下"] },
  { locale: "zh-CN", lines: ["游客能上榜吗", "不能 要登录"] },

  // ── en ──
  { locale: "en", lines: ["anyone on cyber fortune", "yeah stuck on hard mode"] },
  { locale: "en", lines: ["how to tip creators", "game page has a tip button i think"] },
  { locale: "en", lines: ["is this site new", "feels like early access yeah"] },
  { locale: "en", lines: ["void gacha worth it", "free to try just dont expect much"] },
  { locale: "en", lines: ["leaderboard not updating", "u logged in? guest scores dont count"] },
  { locale: "en", lines: ["wave 15 boss tips", "dodge middle lane on triple laser"] },
  { locale: "en", lines: ["anyone beat rhythm fever", "not yet 94% accuracy max"] },
  { locale: "en", lines: ["where forum", "scroll down on the game page"] },
  { locale: "en", lines: ["void relay hard?", "floor 5+ is where it hurts"] },
  { locale: "en", lines: ["ten pull all blues", "welcome to the club"] },
  { locale: "en", lines: ["orbital salvage tips", "upgrade nova turret before wave 5"] },
  { locale: "en", lines: ["ice protocol stuck", "clear patrol routes first"] },
  { locale: "en", lines: ["mobile playable?", "rhythm is rough rest is ok"] },
  { locale: "en", lines: ["just disconnected", "refresh and log back in"] },
  { locale: "en", lines: ["anyone awake", "yeah 3am grind"] },
  { locale: "en", lines: ["got a lucky pull", "nice im jealous"] },
  { locale: "en", lines: ["tips real money?", "preview only no charges"] },
  { locale: "en", lines: ["favorites where", "heart icon on game page"] },
  { locale: "en", lines: ["core defense help", "upgrade core before spamming turrets"] },
  { locale: "en", lines: ["card game cheats?", "idk just play it"] },
  { locale: "en", lines: ["guide anywhere", "forum has threads search it"] },
  { locale: "en", lines: ["pulse fever how", "stack combo til it pops"] },
  { locale: "en", lines: ["playing void gacha?", "yeah stuck abyss 7"] },
  { locale: "en", lines: ["coop?", "think its all solo demos"] },
];

/** 創作者頻道：單句 */
export const AMBIENT_CREATOR_SINGLES: AmbientChatSingle[] = [
  { locale: "zh-HK", content: "剛上傳咗 demo 有空幫手試玩畀意見" },
  { locale: "zh-HK", content: "打賞仲係 preview 唔會真扣款" },
  { locale: "zh-HK", content: "封面圖尺寸有冇人知 上傳頁寫得唔清" },
  { locale: "zh-HK", content: "草稿 save 咗先 聽日先公開" },
  { locale: "zh-HK", content: "論壇有人回報 bug 記得去答" },
  { locale: "zh-HK", content: "平台費而家 0% 早期上傳幾抵" },
  { locale: "zh-HK", content: "devlog 更新咗 順便改咗簡介" },
  { locale: "zh-HK", content: "analytics 瀏覽數好似延遲幾分鐘" },
  { locale: "zh-HK", content: "測試 build 上咗 歡迎去試" },
  { locale: "zh-HK", content: "個 demo iframe 尺寸點調好啲" },
  { locale: "zh-HK", content: "有人用過 api key 未" },
  { locale: "zh-HK", content: "今晚改咗平衡 聽日再推一版" },
  { locale: "zh-HK", content: "玩家留言話太難 我諗緊點改" },
  { locale: "zh-HK", content: "封面換咗張 舊嗰張太暗" },
  { locale: "zh-HK", content: "論壇帖冇人回 有啲尷尬" },
  { locale: "zh-CN", content: "刚传了个 demo 有空帮忙试试给反馈" },
  { locale: "zh-CN", content: "打赏还在预览 不会产生真实扣款" },
  { locale: "zh-CN", content: "封面图尺寸有要求吗 上传页没写太清楚" },
  { locale: "zh-CN", content: "先存草稿了 明天再改公开" },
  { locale: "zh-CN", content: "论坛有人报 bug 记得回复一下" },
  { locale: "zh-CN", content: "早期平台费 0% 现在上传挺划算" },
  { locale: "zh-CN", content: "更新了 devlog 顺便改了简介" },
  { locale: "zh-CN", content: "后台浏览数据好像会延迟几分钟" },
  { locale: "zh-CN", content: "测试 build 上了 欢迎来试" },
  { locale: "zh-CN", content: "demo iframe 尺寸怎么调比较好" },
  { locale: "zh-CN", content: "有人用过 api key 吗" },
  { locale: "zh-CN", content: "今晚改了平衡 明天再推一版" },
  { locale: "zh-CN", content: "玩家留言说太难 我在想要不要改" },
  { locale: "zh-CN", content: "封面换了张 旧那张太暗" },
  { locale: "zh-CN", content: "论坛帖没人回 有点尴尬" },
  { locale: "en", content: "just uploaded a demo build — feedback welcome" },
  { locale: "en", content: "tips are still preview only no real charges" },
  { locale: "en", content: "what cover size do you guys use for uploads" },
  { locale: "en", content: "saved as draft going public tomorrow" },
  { locale: "en", content: "someone reported a bug on my thread gotta check" },
  { locale: "en", content: "0% platform fee during early access is nice" },
  { locale: "en", content: "posted a devlog update and tweaked the description" },
  { locale: "en", content: "analytics page views seem a few mins behind" },
  { locale: "en", content: "test build is up if anyone wants to try" },
  { locale: "en", content: "how do u guys size the demo iframe" },
  { locale: "en", content: "anyone using api keys yet" },
  { locale: "en", content: "nerfed balance tonight pushing again tomorrow" },
  { locale: "en", content: "player said its too hard debating a patch" },
  { locale: "en", content: "swapped cover art old one was too dark" },
  { locale: "en", content: "forum thread got zero replies kinda awkward" },
];

/** 創作者頻道：對答 */
export const AMBIENT_CREATOR_DIALOGUES: AmbientChatDialogue[] = [
  { locale: "zh-HK", lines: ["審核一般要幾耐", "我上次一日左右"] },
  { locale: "zh-HK", lines: ["打賞幾時真上線", "官方話 preview 緊 再等等"] },
  { locale: "zh-HK", lines: ["封面用 png 定 jpg", "png 清晰啲 檔案大啲"] },
  { locale: "zh-HK", lines: ["devlog 有人睇咩", "有啊 唔多但有人"] },
  { locale: "zh-HK", lines: ["api key 點申請", "設定頁面有 自己 generate"] },
  { locale: "zh-HK", lines: ["玩家話太難要改嗎", "睇數據 流失高先改"] },
  { locale: "zh-HK", lines: ["草稿會過期嗎", "唔會 一直留到"] },
  { locale: "zh-HK", lines: ["analytics 準唔準", "大概參考 延遲有"] },
  { locale: "zh-CN", lines: ["审核一般要多久", "我上次一天左右"] },
  { locale: "zh-CN", lines: ["打赏什么时候真上线", "官方说还在预览 再等等"] },
  { locale: "zh-CN", lines: ["封面用 png 还是 jpg", "png 清晰 文件大点"] },
  { locale: "zh-CN", lines: ["devlog 有人看吗", "有 不多但有人"] },
  { locale: "zh-CN", lines: ["api key 怎么申请", "设置页面有 自己 generate"] },
  { locale: "zh-CN", lines: ["玩家说太难要改吗", "看数据 流失高再改"] },
  { locale: "zh-CN", lines: ["草稿会过期吗", "不会 一直留着"] },
  { locale: "zh-CN", lines: ["analytics 准吗", "大概参考 有延迟"] },
  { locale: "en", lines: ["how long does review take", "like a day for me last time"] },
  { locale: "en", lines: ["when tips go live", "still preview afaik"] },
  { locale: "en", lines: ["png or jpg for cover", "png sharper bigger file"] },
  { locale: "en", lines: ["anyone read devlogs", "some ppl yeah not many"] },
  { locale: "en", lines: ["how to get api key", "settings page generate one"] },
  { locale: "en", lines: ["game too hard change it?", "check dropoff first"] },
  { locale: "en", lines: ["do drafts expire", "nah they stick around"] },
  { locale: "en", lines: ["analytics accurate?", "roughly yeah bit delayed"] },
];
