/** 虛擬玩家自我介紹：長短不一，語氣像真人隨手寫的 */
export const VIRTUAL_PLAYER_BIOS: Record<string, string> = {
  // 台港澳 · 繁體
  "hk-01":
    "下海打本之前一定檢查裝備兩遍，第三遍是習慣。輸了先怪自己，唔太甩鍋隊友。周末多半在翻老遊戲，新遊反而慢慢來。",
  "hk-02": "半夜還在線好正常 🌙 鍾意慢慢逛地圖，卡關就去沖杯面，返嚟再諗",
  "hk-03":
    "每張圖角落都要摸一遍先舒服，主線？等等，壁畫仲未睇完。隊友催進度我會扮聽唔到",
  "hk-04": "就差嗰張卡，卡咗快兩年……有多餘的私我 👀",
  "hk-05": "🕹️✨",
  "hk-06":
    "細個喺街機廳大，按鍵手感好緊要。而家反應慢咗，不過套路仲識，新手唔好掉以輕心",
  "hk-07": "放學就打機，功課聽日先講",
  "hk-08": "恐怖遊戲先 pass 🧸",
  "hk-09": "仲練緊",
  "hk-10": "動漫同遊戲各半，兩邊荷包都空",
  "hk-11": "夏天打機一定要開冷氣，唔係手汗會撳錯",
  "hk-12": "打完一鋪去飲凍奶茶，就係咁。檸茶都得",
  "hk-13":
    "塔唔擺到密密麻麻瞓唔著。外賣到了會先食，打完呢波再講——唔好催",
  "hk-14": "放工返嚟先係人生，打幾鋪紓壓就夠，唔追求上分",
  "hk-15": "港島夜深最啱打機，日間嘈到冇辦法認真",
  "hk-16": "街機廳長大，而家改打手機，手感仲喺度",
  "hk-17": "講好最後一鋪……已經第四鋪",
  "hk-18": "能躺著玩就唔企，能單機就唔開語音",
  "hk-19": "連勝好驚斷，斷咗又想追返，循環",
  "hk-20": "節奏遊戲手指先死，腦仲未死",
  "hk-21": "凍奶茶 > 勝利 🧋",
  "hk-22": "圖要全收集先過得自己嗰關，主線慢慢嚟",
  "hk-23": "新手唔恥，恥嘅係唔問就亂衝",
  "hk-24": "存檔位唔夠用，每個轉折都要留一手",
  "hk-25": "雨夜青蛙常客，閒時睇人打機都開心",
  "hk-26": "屋企人瞓緊，靜音打，訊息遲覆唔好怪",
  "hk-27": "排位只係用來證明我真係好菜",
  "hk-28": "平日忙，周末連玩補數，別星期一催我上線",
  "hk-29": "官方路線？我走隱線嗰條先",
  "hk-30": "一命通關派，死咗就關機冷靜",

  // 簡體
  "cn-01": "别催，越催越慢",
  "cn-02": "这ID十年前起的，懂的人自然懂",
  "cn-03": "跪习惯了",
  "cn-04": "打完这局就吃辣条，谁说都不改",
  "cn-05":
    "以前这ID很中二的，现在懒得改了。晚上上线比较多，白天要上班装正常人",
  "cn-06": "哈哈哈哈🤣 别问我 问就是开心",
  "cn-07": "输了是键盘问题，赢了是自己厉害，逻辑完美",
  "cn-08": "混",
  "cn-09": "角落玩比较安心",
  "cn-10": "话不多",
  "cn-11": "有些局打完会想很久，有些打完就忘。游戏是这样，人也差不多",
  "cn-12": "一个人玩惯了，组队会紧张",
  "cn-13": "老游戏骨灰，新作观望半年再说",
  "cn-14": "智商税游戏不碰",
  "cn-15":
    "有些号名字取大了，人没变大。上线就看看论坛，打打轻松的，难的留给年轻人",
  "cn-16": "嗯",
  "cn-17": "🌻☀️",
  "cn-18": "喜欢画风好看的，剧情差一点也能忍",
  "cn-19": "消息不怎么回，看见会点赞",
  "cn-20": "👑？",
  "cn-21": "打着打着就饿了，外卖比副本重要",
  "cn-22": "上线时间不规律，有时连打几小时，有时一周不上。别私信问在不在",
  "cn-23": "🥺💕",
  "cn-24": "说好不肝，结果又三点",
  "cn-25": "路过刷分，别当真",
  "cn-26": "咸鱼翻身中……还在翻",
  "cn-27": "连跪七把后还能说话，说明心态好",
  "cn-28": "咖啡续命，键盘续命，外卖也续命",
  "cn-29": "上班摸鱼时间上线，别开麦",
  "cn-30": "地图钉子户，角落没摸完不下线",
  "cn-31": "节奏苦手，慢半拍是常态",
  "cn-32": "氪金劝退，白嫖快乐",
  "cn-33": "深夜食堂客，边吃边打最香",
  "cn-34": "存档强迫症，每个分歧都要存",
  "cn-35": "路过点赞党，评论很少写",

  // 英文
  "en-01": "mostly here for chill games. ranked stuff stresses me out ngl",
  "en-02": "I play tanks. poorly.",
  "en-03": "YES I TYPE IN CAPS SORRY",
  "en-04": "maybe tomorrow",
  "en-05": "these aren't the stats you're looking for",
  "en-06": "trying to find people to play with lol",
  "en-07": "gg",
  "en-08":
    "late night player. coffee first, maybe ranked later. or not. depends",
  "en-09": "idk",
  "en-10": "fast loads, slow decisions",
  "en-11": "🎉🔥🎉",
  "en-12": "weather's bad so I'm inside. simple math",
  "en-13":
    "support main forever. if we lose it's probably because I went DPS once. sorry",
  "en-14": "my ping is a personality trait at this point",
  "en-15": "wandering through pixel worlds. no rush",
  "en-16": "coffee first. then maybe a boss. or more coffee",
  "en-17": "if I'm stuck, I'm softlocked. if you're stuck, skill issue",
  "en-18": "quiet queue. I listen more than I type",
  "en-19": "brb retrying that fight. again.",
  "en-20": "commute music + neon games = my evening",
  "en-21": "I save. a lot. don't judge",
  "en-22": "phase 1 was easy. phase 2 is personal",
  "en-23": "AFK but watching chat. say hi",
  "en-24": "I live for the combo. the rest is noise",
  "en-25": "loot first, story later",
  "en-26": "main quest? optional. side quests forever",
  "en-27": "blame the input delay. always",
  "en-28": "warmup takes longer than the match. worth it",
  "en-29": "I read patch notes so you don't have to",
  "en-30": "one more run. then sleep. (lying)",
};

export function getVirtualPlayerBio(playerId: string): string | null {
  const bio = VIRTUAL_PLAYER_BIOS[playerId]?.trim();
  return bio || null;
}
